"""
Disney poller Lambda — entrypoint.

Triggered by EventBridge every 2 minutes. For each park:
  1. Fetch live wait/status data from themeparks.wiki
  2. Diff each attraction against the stored STATE row in DynamoDB
  3. Persist the new state and append to history if status changed
  4. For each status transition that warrants an alert, fan out
     Pushover messages to the INTERSECTION of:
       (users subscribed to this park) ∩ (users who favorited THIS ride)

M3 Phase 2: alerts are per-favorite, not per-park. A user subscribed
to "EPCOT" with no favorites in EPCOT receives zero alerts —
intentional, matches Phase 3's "default zero rides → zero alerts"
spec. To get alerts, a user needs BOTH a park subscription AND
favorites in that park.

Subscriber rows: PARK#<key> / USER#<id> (park subscription)
Favorite rows:   USER#<id> / FAV_RIDE#<ride_id>  (with denormalized park_key)
Profile rows:    USER#<id> / PROFILE             (name + pushover_user_key)

Cooldowns are per-ride, not per-recipient: even if zero users get
the alert today (no favoriters), the cooldown is set so flap-induced
status churn doesn't spam if a user adds the favorite mid-window.
"""

import json
import os
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import wait_times
import db
import notifier
import weather

PARK_KEYS = os.environ["PARK_KEYS"].split(",")

# Park-key → display-name lookup used by the weather-shift alert path,
# which doesn't have a live attraction in hand to read park_name from.
# Mirrors the labels themeparks.wiki returns; the regular DOWN/UP
# alerts continue to use attr["park_name"] (the upstream source of
# truth) so a name change in the wild propagates without needing a
# code deploy.
PARK_NAMES = {
    "magic_kingdom":     "Magic Kingdom",
    "epcot":             "EPCOT",
    "hollywood_studios": "Hollywood Studios",
    "animal_kingdom":    "Animal Kingdom",
}
SECOND_ALERT_MINS = int(os.environ.get("SECOND_ALERT_MINS", "45"))

# Suppress alerts within this many minutes of park close — rides
# routinely shut down for the night around then and we don't want
# the closing-time wave of "X is DOWN" pings.
CLOSING_BUFFER_MINS = int(os.environ.get("CLOSING_BUFFER_MINS", "30"))

# Eastern (the parks' tz). Used for the per-(ride, hour) low-wait
# threshold lookup so the bucket the poller compares against matches
# what tools/aggregate-analytics.py emitted.
_EASTERN = ZoneInfo("America/New_York")

# Short-wait alert thresholds, generated by tools/aggregate-analytics.py
# from the historical wait_history snapshot. Bundled into the Lambda
# asset by CDK; loaded once at cold start. Schema documented in the
# generator. Missing rides / hours mean "no threshold → don't alert."
_BASELINES_PATH = Path(__file__).resolve().parent / "baselines.json"
try:
    _baselines = json.loads(_BASELINES_PATH.read_text())
    _LOW_WAIT_THRESHOLDS: dict[str, dict[str, int]] = _baselines.get("rides", {})
    print(
        f"[poller] loaded low-wait thresholds for {len(_LOW_WAIT_THRESHOLDS)} rides "
        f"(generated {_baselines.get('generated_at', '?')})"
    )
except FileNotFoundError:
    _LOW_WAIT_THRESHOLDS = {}
    print("[poller] no baselines.json — short-wait alerts disabled")


def _low_wait_threshold(ride_id: str, hour_et: int) -> int | None:
    """Threshold for this (ride, ET hour), or None if untracked."""
    by_hour = _LOW_WAIT_THRESHOLDS.get(ride_id)
    if not by_hour:
        return None
    return by_hour.get(str(hour_et))


def handler(event, context):
    """EventBridge invokes this with no meaningful payload — the schedule
    *is* the trigger. We process every park on every invocation."""
    started = time.time()
    print(f"[poller] Starting poll of {len(PARK_KEYS)} parks: {PARK_KEYS}")

    # Cache subscribers per park so we don't re-query DynamoDB for
    # every ride event.
    subscribers_by_park: dict[str, list[str]] = {}
    profile_cache: dict[str, dict] = {}

    # M3 Phase 2: per-(user, park) favorite-rides cache. Looked up
    # lazily — only queried for users actually subscribed to a park
    # we're processing. One Query per (user × park) per invocation.
    # At ~10 users × 4 parks = 40 queries per poll = ~28K/day, well
    # within free tier.
    favorites_cache: dict[tuple[str, str], set[str]] = {}

    # Cache park hours per park (one schedule call per invocation).
    # Returns True if alerts should fire for this park right now,
    # False during closed hours / closing buffer / when schedule
    # fetch fails (fail-open: see comment in _alerts_allowed).
    alerts_allowed_cache: dict[str, bool] = {}

    def alerts_allowed(park_key: str) -> bool:
        if park_key in alerts_allowed_cache:
            return alerts_allowed_cache[park_key]
        hours = wait_times.fetch_park_hours(park_key)
        if hours is None:
            # Fail-open: if the schedule API is broken or returns
            # nothing, prefer to alert (data we miss is worse than
            # noise). This matches the Pi version's implicit behavior.
            print(f"[poller] No schedule for {park_key} — defaulting to alerts ON")
            alerts_allowed_cache[park_key] = True
            return True
        open_dt, close_dt = hours
        now_eastern = datetime.now(open_dt.tzinfo)
        cutoff = close_dt - timedelta(minutes=CLOSING_BUFFER_MINS)
        allowed = open_dt <= now_eastern <= cutoff
        if not allowed:
            print(
                f"[poller] {park_key}: alerts SUPPRESSED — "
                f"now={now_eastern.strftime('%H:%M')}, "
                f"open={open_dt.strftime('%H:%M')}, "
                f"close-buffer={cutoff.strftime('%H:%M')}"
            )
        alerts_allowed_cache[park_key] = allowed
        return allowed

    def get_subscribers(park_key: str) -> list[str]:
        if park_key not in subscribers_by_park:
            subscribers_by_park[park_key] = db.get_park_subscribers(park_key)
        return subscribers_by_park[park_key]

    def get_user_key(user_id: str) -> str | None:
        if user_id not in profile_cache:
            profile = db.get_user_profile(user_id) or {}
            profile_cache[user_id] = profile
        return profile_cache.get(user_id, {}).get("pushover_user_key")

    def get_favorites(user_id: str, park_key: str) -> set[str]:
        """Lazily fetch + cache one user's favorites for one park."""
        cache_key = (user_id, park_key)
        if cache_key not in favorites_cache:
            favorites_cache[cache_key] = db.get_user_favorites_for_park(user_id, park_key)
        return favorites_cache[cache_key]

    def filter_to_favoriters(
        subscribers: list[str], park_key: str, ride_id: str
    ) -> list[str]:
        """Of these park-subscribers, return only those who favorited THIS ride.

        M3 Phase 2 alert intersection: alerts for a ride event go to
        the set of users who BOTH (a) subscribed to the park AND
        (b) marked that specific ride as a favorite. A user with
        zero favorites in a park gets zero alerts for that park —
        intentional, matches Phase 3's "default zero rides → zero
        alerts" spec.
        """
        return [s for s in subscribers if ride_id in get_favorites(s, park_key)]

    # Plan-aware alerts (M9 bridge): build a {ride_identifier: [(user,
    # plan_id), ...]} index of today's active plans ONCE per invocation,
    # used to fan out plan-disruption Pushovers on DOWN/BACK UP
    # transitions in addition to the favoriter fanout. The same scan
    # also yields a per-plan summary used by the weather-shift fanout
    # below. Failure here is bonus-feature-degrades-gracefully — the
    # favoriter alerts above still fire normally.
    # Counters initialized here (before the weather block) so the
    # weather-shift fanout below can contribute to the same totals as
    # the per-ride fanouts that follow.
    total_changes = 0
    total_alerts = 0

    today_local_iso = datetime.now(_EASTERN).date().isoformat()
    plan_ride_index, active_plans = db.build_active_plan_ride_index(today_local_iso)
    if plan_ride_index:
        print(
            f"[poller] Active plans for {today_local_iso}: "
            f"{sum(len(v) for v in plan_ride_index.values())} ride-targets "
            f"across {len(plan_ride_index)} distinct ride identifiers, "
            f"{len(active_plans)} plan(s) total"
        )

    # ── Plan-weather-shift alert path ──────────────────────────────
    # Sibling of the per-ride DOWN/UP plan-disruption alerts above:
    # detect when a thunderstorm newly appears in the next-6h forecast
    # while users have active plans for today, and fire one Pushover
    # per affected plan (deduped to one per user, since the weather
    # itself is park-agnostic and a user with two MK plans today gets
    # the same actionable signal once).
    #
    # Cost gate: only fetch weather when at least one active plan
    # exists for today. Off-season days with no plans skip the HTTP
    # call entirely.
    if active_plans:
        new_weather = weather.fetch_forecast()
        if new_weather is not None:
            prior_weather = db.get_prior_weather_snapshot()
            shift = weather.detect_storm_shift(prior_weather, new_weather)
            # Persist the new snapshot regardless of shift — this is
            # what next poll compares against. Write AFTER detect so a
            # spurious write that altered the payload can't mask the
            # detection result.
            db.put_weather_snapshot(new_weather)
            if shift:
                window_phrase = weather.format_storm_window(shift)
                print(
                    f"[poller] Weather shift detected: storm at "
                    f"{shift.get('first_storm_at')} "
                    f"(code {shift.get('first_storm_code')}, "
                    f"{shift.get('next_6h_hit_count')} of next 6h). "
                    f"Fanning out to {len(active_plans)} plan(s)."
                )
                seen_users: set[str] = set()
                weather_alerts_sent = 0
                for plan in active_plans:
                    user_id = plan["user_id"]
                    plan_id = plan["plan_id"]
                    park_key = plan.get("park_key") or "magic_kingdom"
                    # Dedup by user: if a single user has multiple
                    # active plans (unusual but possible — e.g., a
                    # family member planning back-to-back days who
                    # left yesterday's plan unrecorded), they get one
                    # alert, not N.
                    if user_id in seen_users:
                        continue
                    if db.is_weather_alert_on_cooldown(user_id, plan_id):
                        continue
                    user_key = get_user_key(user_id)
                    if not user_key:
                        continue
                    # Mark BEFORE send: same pattern as the other
                    # cooldowns. If the Pushover send fails the
                    # cooldown still prevents re-fire spam within the
                    # window; the user can also check the dashboard.
                    db.mark_weather_alert_sent(user_id, plan_id)
                    park_name = PARK_NAMES.get(park_key, park_key.replace("_", " ").title())
                    if notifier.alert_plan_weather_shift(
                        user_key,
                        park_name=park_name,
                        park_key=park_key,
                        window_phrase=window_phrase,
                        plan_id=plan_id,
                    ):
                        weather_alerts_sent += 1
                        seen_users.add(user_id)
                if weather_alerts_sent:
                    print(
                        f"[poller] Weather-shift alerts sent: "
                        f"{weather_alerts_sent} user(s)"
                    )
                    total_alerts += weather_alerts_sent

    # Track rides currently down across all parks for the post-loop
    # "second alert" sweep (rides down >= SECOND_ALERT_MINS get a
    # follow-up notification).
    currently_down: list[tuple[str, dict]] = []  # (ride_id, attraction)

    for park_key in PARK_KEYS:
        try:
            attractions = wait_times.fetch_live_data(park_key)
        except Exception as e:
            print(f"[poller] ERROR fetching {park_key}: {e}")
            continue

        print(f"[poller] {park_key}: {len(attractions)} attractions")
        subscribers = get_subscribers(park_key)
        now_dt = datetime.now(timezone.utc)
        now_iso = now_dt.isoformat()

        for attr in attractions:
            ride_id = attr["id"]
            new_status = attr["status"]
            new_wait = attr["wait_mins"]

            existing = db.get_ride(ride_id)
            old_status = existing["status"] if existing else None

            db.upsert_ride(attr)

            # Phase A2: persist this poll's forecast snapshot (when
            # upstream provided one) into a FORECAST# sub-row. Wrapped
            # so a forecast-side failure can never break the alert path
            # — a missed forecast is a rounding error against an
            # 8.8M-row historical baseline; a missed alert is a real
            # demo regression. Skip cleanly when the ride has no
            # forecast (DOWN rides, walk-up meets, transportation).
            if attr.get("forecast"):
                try:
                    db.record_forecast(ride_id, attr["last_seen"], attr["forecast"])
                except Exception as e:
                    print(f"[poller] forecast write failed for {attr['name']}: {e}")

            # First time we've seen this ride — record state, no alert.
            if old_status is None:
                continue

            # Track down state regardless of alert fanout, so the
            # "back up" duration and "still down" sweep work even if
            # nobody was subscribed at the time it went down.
            if new_status == "DOWN":
                currently_down.append((ride_id, attr))

            # ── LOW WAIT: current wait below per-(ride, hour) baseline ─
            # Fires on any operating poll where current wait drops
            # below what's typical for this attraction at this hour.
            # Independent of status-change detection — this is the
            # only alert type that fires on stable-state polls. Park-
            # hours and cooldown still gate the actual fanout.
            if (
                new_status == "OPERATING"
                and new_wait is not None
                and alerts_allowed(park_key)
            ):
                threshold = _low_wait_threshold(
                    ride_id, datetime.now(_EASTERN).hour
                )
                if (
                    threshold is not None
                    and new_wait <= threshold
                    and not db.is_low_wait_alert_on_cooldown(ride_id)
                ):
                    favoriters = filter_to_favoriters(subscribers, park_key, ride_id)
                    if favoriters:
                        # Cooldown is set per-ride (not per-recipient)
                        # — same pattern as DOWN. Even with zero
                        # current favoriters we'd still set it to
                        # avoid flap-induced spam if a user adds
                        # the favorite mid-window. But here we only
                        # set it WHEN we actually fan out so a low-
                        # wait window with no favoriters can still
                        # alert the next user who favorites the ride.
                        db.mark_low_wait_alert_sent(ride_id)
                        # Use the threshold as a stand-in for "typical"
                        # — it's actually the half-of-typical floor,
                        # but it's close enough for the user-facing
                        # phrasing and gives them a single number.
                        typical_for_msg = threshold * 2
                        print(
                            f"[poller] {attr['name']} LOW WAIT ({new_wait}m vs ~{typical_for_msg}m typical): "
                            f"alerting {len(favoriters)} favoriters"
                        )
                        total_alerts += _fanout(
                            favoriters, get_user_key,
                            notifier.alert_low_wait,
                            ride_name=attr["name"],
                            park_name=attr["park_name"],
                            park_key=park_key,
                            wait_mins=new_wait,
                            typical_wait_mins=typical_for_msg,
                        )

            # No status change → nothing more to do for this ride.
            if new_status == old_status:
                continue

            total_changes += 1
            db.record_status_change(
                ride_id=ride_id,
                ride_name=attr["name"],
                park_name=attr["park_name"],
                park_key=park_key,
                old_status=old_status,
                new_status=new_status,
                wait_mins=new_wait,
                changed_at=now_iso,
            )

            # ── DOWN: just went out of service ─────────────────────
            if new_status == "DOWN":
                db.set_down_since(ride_id, now_dt)

                # Park-hours gate: still record the change above (so
                # analytics + DOWN_SINCE tracking work), but don't
                # send the alert if we're outside operating hours or
                # within the closing buffer.
                if not alerts_allowed(park_key):
                    continue

                # Cooldown check: don't re-alert if we already pinged
                # for this ride in the last DOWN_ALERT_COOLDOWN_SECS.
                # (Themeparks.wiki occasionally flaps a ride
                # OPERATING→DOWN→OPERATING within minutes.)
                if db.is_down_alert_on_cooldown(ride_id):
                    print(f"[poller] Skipping DOWN alert for {attr['name']} (cooldown)")
                    continue

                # Cooldown is set per-ride (not per-recipient) on
                # purpose: even if zero users get the alert today
                # (no one favorited this ride), we still want the
                # cooldown to prevent flap-induced spam if a user
                # adds the favorite mid-window. They'll catch the
                # next event.
                db.mark_down_alert_sent(ride_id)
                favoriters = filter_to_favoriters(subscribers, park_key, ride_id)
                print(
                    f"[poller] {attr['name']} DOWN: {len(subscribers)} park subs, "
                    f"{len(favoriters)} favoriters → alerting"
                )
                total_alerts += _fanout(
                    favoriters, get_user_key,
                    notifier.alert_ride_down,
                    ride_name=attr["name"],
                    park_name=attr["park_name"],
                    park_key=park_key,
                )

                # Plan-aware fanout: users who don't favorite this
                # ride but have it in TODAY's active plan still want
                # to know — it's an actionable replan trigger.
                # Piggybacks on the per-ride DOWN cooldown above so we
                # don't re-alert on flap.
                plan_targets = db.lookup_plan_targets(
                    plan_ride_index, ride_id, attr["name"]
                )
                if plan_targets:
                    favoriter_set = set(favoriters)
                    plan_alert_count = 0
                    for target_user, target_plan in plan_targets:
                        # If this user is already getting the
                        # favoriter alert, skip the plan alert —
                        # one notification per event is enough.
                        if target_user in favoriter_set:
                            continue
                        user_key = get_user_key(target_user)
                        if not user_key:
                            continue
                        if notifier.alert_plan_disruption(
                            user_key,
                            ride_name=attr["name"],
                            park_name=attr["park_name"],
                            park_key=park_key,
                            disruption_type="went_down",
                            plan_id=target_plan,
                        ):
                            plan_alert_count += 1
                    if plan_alert_count:
                        print(
                            f"[poller] {attr['name']} DOWN: "
                            f"{plan_alert_count} plan-aware alerts (non-favoriter)"
                        )
                        total_alerts += plan_alert_count

            # ── BACK UP: was DOWN, now OPERATING ───────────────────
            elif new_status == "OPERATING" and old_status == "DOWN":
                went_down = db.get_down_since(ride_id)
                actual_mins = None
                if went_down:
                    actual_mins = round((now_dt - went_down).total_seconds() / 60)
                db.clear_down_since(ride_id)

                # Park-hours gate also applies to "back up" alerts —
                # if we suppressed the DOWN alert at park-close, the
                # matching UP alert at park-open the next morning
                # would be confusing context-free noise.
                if not alerts_allowed(park_key):
                    continue

                # Cooldown gate: flap protection. themeparks.wiki
                # sometimes reports a ride OPERATING→DOWN→OPERATING
                # repeatedly within minutes. Without this, every UP
                # transition fires a fresh BACK UP push. We still
                # record the state transition (above) so DOWN_SINCE
                # is cleared correctly; we just skip the alert.
                if db.is_back_up_alert_on_cooldown(ride_id):
                    print(f"[poller] Skipping BACK UP alert for {attr['name']} (cooldown)")
                    continue

                # Set cooldown BEFORE fanning out, same pattern as
                # DOWN cooldown — even if no users get pinged today
                # (no favoriters, no plan watchers), we still want
                # the cooldown to prevent flap spam if a user adds
                # the favorite / plan mid-window.
                db.mark_back_up_alert_sent(ride_id)

                favoriters = filter_to_favoriters(subscribers, park_key, ride_id)
                print(
                    f"[poller] {attr['name']} BACK UP: {len(subscribers)} park subs, "
                    f"{len(favoriters)} favoriters → alerting"
                )
                total_alerts += _fanout(
                    favoriters, get_user_key,
                    notifier.alert_ride_up,
                    ride_name=attr["name"],
                    park_name=attr["park_name"],
                    park_key=park_key,
                    wait_mins=new_wait,
                    actual_downtime_mins=actual_mins,
                )

                # Plan-aware fanout for the back-up direction. Same
                # dedup as DOWN: skip users already getting the
                # favoriter notification.
                plan_targets = db.lookup_plan_targets(
                    plan_ride_index, ride_id, attr["name"]
                )
                if plan_targets:
                    favoriter_set = set(favoriters)
                    plan_alert_count = 0
                    for target_user, target_plan in plan_targets:
                        if target_user in favoriter_set:
                            continue
                        user_key = get_user_key(target_user)
                        if not user_key:
                            continue
                        if notifier.alert_plan_disruption(
                            user_key,
                            ride_name=attr["name"],
                            park_name=attr["park_name"],
                            park_key=park_key,
                            disruption_type="back_up",
                            plan_id=target_plan,
                            wait_mins=new_wait,
                        ):
                            plan_alert_count += 1
                    if plan_alert_count:
                        print(
                            f"[poller] {attr['name']} BACK UP: "
                            f"{plan_alert_count} plan-aware alerts (non-favoriter)"
                        )
                        total_alerts += plan_alert_count

            # CLOSED transitions intentionally don't alert — too noisy
            # at park closing time.

    # ── Second alert sweep: rides down >= SECOND_ALERT_MINS ───────
    # Runs once per invocation after all parks processed.
    for ride_id, attr in currently_down:
        # Park-hours gate applies here too — no "still down" pings
        # at 11pm just because the ride went down at park-close.
        if not alerts_allowed(attr["park_key"]):
            continue
        went_down = db.get_down_since(ride_id)
        if not went_down:
            continue
        elapsed_mins = (datetime.now(timezone.utc) - went_down).total_seconds() / 60
        if elapsed_mins < SECOND_ALERT_MINS:
            continue

        # Use a separate cooldown key so the still-down alert doesn't
        # collide with the initial DOWN cooldown.
        cooldown_pk = f"RIDE#{ride_id}"
        cooldown_sk = "COOLDOWN#STILL_DOWN"
        # Reuse the same TTL helper by writing directly — small enough
        # to inline here without bloating db.py.
        from db import _table  # type: ignore
        existing_cooldown = _table.get_item(Key={"PK": cooldown_pk, "SK": cooldown_sk}).get("Item")
        if existing_cooldown:
            continue
        expire_ts = int(time.time()) + (SECOND_ALERT_MINS * 60)
        _table.put_item(Item={
            "PK": cooldown_pk,
            "SK": cooldown_sk,
            "sent_at": datetime.now(timezone.utc).isoformat(),
            "ttl": expire_ts,
        })

        subscribers = get_subscribers(attr["park_key"])
        favoriters = filter_to_favoriters(subscribers, attr["park_key"], ride_id)
        print(
            f"[poller] {attr['name']} STILL DOWN ({int(elapsed_mins)}m): "
            f"{len(subscribers)} park subs, {len(favoriters)} favoriters → alerting"
        )
        total_alerts += _fanout(
            favoriters, get_user_key,
            notifier.alert_still_down,
            ride_name=attr["name"],
            park_name=attr["park_name"],
            park_key=attr["park_key"],
            minutes_down=int(elapsed_mins),
        )

    elapsed = time.time() - started
    print(
        f"[poller] Done. {total_changes} status changes, "
        f"{total_alerts} alerts sent, {elapsed:.1f}s elapsed"
    )
    return {
        "status": "ok",
        "parks_polled": len(PARK_KEYS),
        "changes": total_changes,
        "alerts_sent": total_alerts,
        "elapsed_secs": round(elapsed, 1),
    }


def _fanout(subscribers: list[str], get_user_key, alert_fn, **kwargs) -> int:
    """Send the same alert to every subscriber. Returns count sent."""
    sent = 0
    for user_id in subscribers:
        user_key = get_user_key(user_id)
        if not user_key:
            print(f"[poller] No pushover_user_key for user {user_id} — skipping")
            continue
        if alert_fn(user_key, **kwargs):
            sent += 1
    return sent
