"""
Disney poller Lambda — entrypoint.

Triggered by EventBridge every 2 minutes. For each park:
  1. Fetch live wait/status data from themeparks.wiki
  2. Diff each attraction against the stored STATE row in DynamoDB
  3. Persist the new state and append to history if status changed
  4. For each status transition that warrants an alert, fan out
     Pushover messages to the INTERSECTION of:
       (users subscribed to this park) ∩ (users who favorited THIS ride)

M3 Phase 2: alerts are per-favorite, not per-park. A user subscribed
to "EPCOT" with no favorites in EPCOT receives zero alerts —
intentional, matches Phase 3's "default zero rides → zero alerts"
spec. To get alerts, a user needs BOTH a park subscription AND
favorites in that park.

Subscriber rows: PARK#<key> / USER#<id> (park subscription)
Favorite rows:   USER#<id> / FAV_RIDE#<ride_id>  (with denormalized park_key)
Profile rows:    USER#<id> / PROFILE             (name + pushover_user_key)

Cooldowns are per-ride, not per-recipient: even if zero users get
the alert today (no favoriters), the cooldown is set so flap-induced
status churn doesn't spam if a user adds the favorite mid-window.
"""

import json
import os
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import wait_times
import db
import notifier
import weather
import alert_routing
import forecast_signal

PARK_KEYS = os.environ["PARK_KEYS"].split(",")

# Park-key → display-name lookup used by the weather-shift alert path,
# which doesn't have a live attraction in hand to read park_name from.
# Mirrors the labels themeparks.wiki returns; the regular DOWN/UP
# alerts continue to use attr["park_name"] (the upstream source of
# truth) so a name change in the wild propagates without needing a
# code deploy.
PARK_NAMES = {
    "magic_kingdom":     "Magic Kingdom",
    "epcot":             "EPCOT",
    "hollywood_studios": "Hollywood Studios",
    "animal_kingdom":    "Animal Kingdom",
}
SECOND_ALERT_MINS = int(os.environ.get("SECOND_ALERT_MINS", "45"))

# Suppress alerts within this many minutes of park close — rides
# routinely shut down for the night around then and we don't want
# the closing-time wave of "X is DOWN" pings.
CLOSING_BUFFER_MINS = int(os.environ.get("CLOSING_BUFFER_MINS", "30"))

# Eastern (the parks' tz). Used for the per-(ride, hour) low-wait
# threshold lookup so the bucket the poller compares against matches
# what tools/aggregate-analytics.py emitted.
_EASTERN = ZoneInfo("America/New_York")

# Short-wait alert thresholds, generated by tools/aggregate-analytics.py
# from the historical wait_history snapshot. Bundled into the Lambda
# asset by CDK; loaded once at cold start. Schema documented in the
# generator. Missing rides / hours mean "no threshold → don't alert."
_BASELINES_PATH = Path(__file__).resolve().parent / "baselines.json"
try:
    _baselines = json.loads(_BASELINES_PATH.read_text())
    _LOW_WAIT_THRESHOLDS: dict[str, dict[str, int]] = _baselines.get("rides", {})
    print(
        f"[poller] loaded low-wait thresholds for {len(_LOW_WAIT_THRESHOLDS)} rides "
        f"(generated {_baselines.get('generated_at', '?')})"
    )
except FileNotFoundError:
    _LOW_WAIT_THRESHOLDS = {}
    print("[poller] no baselines.json — short-wait alerts disabled")


def _low_wait_threshold(ride_id: str, hour_et: int) -> int | None:
    """Threshold for this (ride, ET hour), or None if untracked."""
    by_hour = _LOW_WAIT_THRESHOLDS.get(ride_id)
    if not by_hour:
        return None
    return by_hour.get(str(hour_et))


# Minimum minutes-earlier for an LL improvement to be worth a push. A
# 5-min improvement isn't actionable; this kills that triviality. (The
# deeper "you already hold an LL hours earlier" case needs the held-LL
# record — see the held-LL precision work.) Env-tunable.
LL_MIN_IMPROVEMENT_MIN = int(os.environ.get("LL_MIN_IMPROVEMENT_MIN", "20"))


def _ll_became_earlier(prior_ll: dict | None, new_ll: dict | None) -> bool:
    """True when a ride's Lightning Lane return window moved MEANINGFULLY
    earlier than the prior poll (>= LL_MIN_IMPROVEMENT_MIN) — the LL-watch
    trigger.

    The STATE row's ll is overwritten each poll, so `prior_ll` is exactly
    last poll's offer: no separate baseline needed. Parsed to datetimes
    (not lexical string compare) so a tz-offset or format change can't
    silently invert the comparison. First appearance (no prior return
    time) is NOT "earlier" — it's a different signal, deferred.
    """
    new_rs = _parse_iso((new_ll or {}).get("return_start"))
    old_rs = _parse_iso((prior_ll or {}).get("return_start"))
    if new_rs is None or old_rs is None:
        return False
    improvement_min = (old_rs - new_rs).total_seconds() / 60
    return improvement_min >= LL_MIN_IMPROVEMENT_MIN


def _parse_iso(iso: str | None):
    if not iso:
        return None
    try:
        return datetime.fromisoformat(iso)
    except (ValueError, TypeError):
        return None


# Minutes of net drift (summed predicted − current across comparable
# remaining rides) at/above which we nudge a re-plan. Env-tunable.
PLAN_DRIFT_THRESHOLD_MIN = int(os.environ.get("PLAN_DRIFT_THRESHOLD_MIN", "30"))

# Plan-drift is OFF by default: predicted_wait_min bakes in Lightning
# Lane assumptions (an LL'd headliner is predicted ~15 min), so comparing
# it to the current STANDBY wait falsely reads "busier than planned" for
# every LL ride. Re-enable only once the held-LL record lets the drift
# math exclude LL rides (or compare LL-return-vs-held). Env: "true".
PLAN_DRIFT_ENABLED = os.environ.get("PLAN_DRIFT_ENABLED", "false").lower() == "true"


def _compute_plan_drift(rides: list[dict], current_waits: dict[str, int]):
    """Sum (predicted_wait_min − current_wait) over remaining planned
    rides that have BOTH a numeric prediction and a current operating
    wait. Returns (net_minutes, n_compared): net > 0 = running LIGHTER
    than planned (waits under prediction — time freed up); net < 0 =
    HEAVIER. n_compared guards against firing on a single ride.
    """
    net = 0
    n = 0
    for r in rides:
        rid = r.get("ride_id")
        pred = r.get("predicted_wait_min")
        cur = current_waits.get(rid)
        if rid is None or pred is None or cur is None:
            continue
        try:
            net += int(pred) - int(cur)
        except (TypeError, ValueError):
            continue
        n += 1
    return net, n


def handler(event, context):
    """EventBridge invokes this with no meaningful payload — the schedule
    *is* the trigger. We process every park on every invocation."""
    started = time.time()
    print(f"[poller] Starting poll of {len(PARK_KEYS)} parks: {PARK_KEYS}")

    # Cache subscribers per park so we don't re-query DynamoDB for
    # every ride event.
    subscribers_by_park: dict[str, list[str]] = {}
    profile_cache: dict[str, dict] = {}

    # M3 Phase 2: per-(user, park) favorite-rides cache. Looked up
    # lazily — only queried for users actually subscribed to a park
    # we're processing. One Query per (user × park) per invocation.
    # At ~10 users × 4 parks = 40 queries per poll = ~28K/day, well
    # within free tier.
    favorites_cache: dict[tuple[str, str], set[str]] = {}

    # LL-watch opt-ins per (user, park) — favorites with ll_watch=true.
    # Same lazy-cache shape as favorites_cache; only queried for park
    # subscribers when an LL improvement actually fires.
    ll_watch_cache: dict[tuple[str, str], set[str]] = {}

    # Cache park hours per park (one schedule call per invocation).
    # Returns True if alerts should fire for this park right now,
    # False during closed hours / closing buffer / when schedule
    # fetch fails (fail-open: see comment in _alerts_allowed).
    alerts_allowed_cache: dict[str, bool] = {}

    def alerts_allowed(park_key: str) -> bool:
        if park_key in alerts_allowed_cache:
            return alerts_allowed_cache[park_key]
        hours = wait_times.fetch_park_hours(park_key)
        if hours is None:
            # Fail-open: if the schedule API is broken or returns
            # nothing, prefer to alert (data we miss is worse than
            # noise). This matches the Pi version's implicit behavior.
            print(f"[poller] No schedule for {park_key} — defaulting to alerts ON")
            alerts_allowed_cache[park_key] = True
            return True
        open_dt, close_dt = hours
        now_eastern = datetime.now(open_dt.tzinfo)
        cutoff = close_dt - timedelta(minutes=CLOSING_BUFFER_MINS)
        allowed = open_dt <= now_eastern <= cutoff
        if not allowed:
            print(
                f"[poller] {park_key}: alerts SUPPRESSED — "
                f"now={now_eastern.strftime('%H:%M')}, "
                f"open={open_dt.strftime('%H:%M')}, "
                f"close-buffer={cutoff.strftime('%H:%M')}"
            )
        alerts_allowed_cache[park_key] = allowed
        return allowed

    def get_subscribers(park_key: str) -> list[str]:
        if park_key not in subscribers_by_park:
            subscribers_by_park[park_key] = db.get_park_subscribers(park_key)
        return subscribers_by_park[park_key]

    def get_user_key(user_id: str) -> str | None:
        if user_id not in profile_cache:
            profile = db.get_user_profile(user_id) or {}
            profile_cache[user_id] = profile
        return profile_cache.get(user_id, {}).get("pushover_user_key")

    def get_favorites(user_id: str, park_key: str) -> set[str]:
        """Lazily fetch + cache one user's favorites for one park."""
        cache_key = (user_id, park_key)
        if cache_key not in favorites_cache:
            favorites_cache[cache_key] = db.get_user_favorites_for_park(user_id, park_key)
        return favorites_cache[cache_key]

    def get_ll_watched(user_id: str, park_key: str) -> set[str]:
        """Lazily fetch + cache the rides a user opted into LL-watching."""
        cache_key = (user_id, park_key)
        if cache_key not in ll_watch_cache:
            ll_watch_cache[cache_key] = db.get_user_ll_watched_rides(user_id, park_key)
        return ll_watch_cache[cache_key]

    def filter_to_favoriters(
        subscribers: list[str], park_key: str, ride_id: str
    ) -> list[str]:
        """Of these park-subscribers, return only those who favorited THIS ride.

        M3 Phase 2 alert intersection: alerts for a ride event go to
        the set of users who BOTH (a) subscribed to the park AND
        (b) marked that specific ride as a favorite. A user with
        zero favorites in a park gets zero alerts for that park —
        intentional, matches Phase 3's "default zero rides → zero
        alerts" spec.
        """
        return [s for s in subscribers if ride_id in get_favorites(s, park_key)]

    # Plan-aware alerts (M9 bridge): build a {ride_identifier: [(user,
    # plan_id), ...]} index of today's active plans ONCE per invocation,
    # used to fan out plan-disruption Pushovers on DOWN/BACK UP
    # transitions in addition to the favoriter fanout. The same scan
    # also yields a per-plan summary used by the weather-shift fanout
    # below. Failure here is bonus-feature-degrades-gracefully — the
    # favoriter alerts above still fire normally.
    # Counters initialized here (before the weather block) so the
    # weather-shift fanout below can contribute to the same totals as
    # the per-ride fanouts that follow.
    total_changes = 0
    total_alerts = 0

    now_et = datetime.now(_EASTERN)
    today_local_iso = now_et.date().isoformat()
    plan_ride_index, active_plans = db.build_active_plan_ride_index(
        today_local_iso, now_et=now_et
    )
    # ride_id → held-LL return ISO, flattened across active plans. Used to
    # suppress useless earlier-LL alerts: if you hold an LL for a ride,
    # only alert when an available slot beats the time you hold.
    held_ll_by_ride: dict[str, str] = {}
    for _p in active_plans:
        for _rid, _ret in (_p.get("ll_holds") or {}).items():
            if _rid and _ret:
                held_ll_by_ride.setdefault(_rid, _ret)
    if plan_ride_index:
        print(
            f"[poller] Active plans for {today_local_iso}: "
            f"{sum(len(v) for v in plan_ride_index.values())} ride-targets "
            f"across {len(plan_ride_index)} distinct ride identifiers, "
            f"{len(active_plans)} plan(s) total"
        )

    # ── Plan-weather-shift alert path ──────────────────────────────
    # Sibling of the per-ride DOWN/UP plan-disruption alerts above:
    # detect when a thunderstorm newly appears in the next-6h forecast
    # while users have active plans for today, and fire one Pushover
    # per affected plan (deduped to one per user, since the weather
    # itself is park-agnostic and a user with two MK plans today gets
    # the same actionable signal once).
    #
    # Cost gate: only fetch weather when at least one active plan
    # exists for today. Off-season days with no plans skip the HTTP
    # call entirely.
    if active_plans:
        new_weather = weather.fetch_forecast()
        if new_weather is not None:
            prior_weather = db.get_prior_weather_snapshot()
            shift = weather.detect_storm_shift(prior_weather, new_weather)
            # Persist the new snapshot regardless of shift — this is
            # what next poll compares against. Write AFTER detect so a
            # spurious write that altered the payload can't mask the
            # detection result.
            db.put_weather_snapshot(new_weather)
            if shift:
                window_phrase = weather.format_storm_window(shift)
                print(
                    f"[poller] Weather shift detected: storm at "
                    f"{shift.get('first_storm_at')} "
                    f"(code {shift.get('first_storm_code')}, "
                    f"{shift.get('next_6h_hit_count')} of next 6h). "
                    f"Fanning out to {len(active_plans)} plan(s)."
                )
                seen_users: set[str] = set()
                seen_user_keys: set[str] = set()
                weather_alerts_sent = 0
                for plan in active_plans:
                    user_id = plan["user_id"]
                    plan_id = plan["plan_id"]
                    park_key = plan.get("park_key") or "magic_kingdom"
                    # Dedup by user: if a single user has multiple
                    # active plans (unusual but possible — e.g., a
                    # family member planning back-to-back days who
                    # left yesterday's plan unrecorded), they get one
                    # alert, not N.
                    if user_id in seen_users:
                        continue
                    if db.is_weather_alert_on_cooldown(user_id, plan_id):
                        continue
                    user_key = get_user_key(user_id)
                    if not user_key:
                        continue
                    # ...and by Pushover key: the owner is implicit AND may
                    # be opted in under their sub via the web toggle — same
                    # key, one push (mirrors dedupe_resolved_by_key).
                    if user_key in seen_user_keys:
                        continue
                    seen_user_keys.add(user_key)
                    # Mark BEFORE send: same pattern as the other
                    # cooldowns. If the Pushover send fails the
                    # cooldown still prevents re-fire spam within the
                    # window; the user can also check the dashboard.
                    db.mark_weather_alert_sent(user_id, plan_id)
                    park_name = PARK_NAMES.get(park_key, park_key.replace("_", " ").title())
                    if notifier.alert_plan_weather_shift(
                        user_key,
                        park_name=park_name,
                        park_key=park_key,
                        window_phrase=window_phrase,
                        plan_id=plan_id,
                    ):
                        weather_alerts_sent += 1
                        seen_users.add(user_id)
                if weather_alerts_sent:
                    print(
                        f"[poller] Weather-shift alerts sent: "
                        f"{weather_alerts_sent} user(s)"
                    )
                    total_alerts += weather_alerts_sent

    # Track rides currently down across all parks for the post-loop
    # "second alert" sweep (rides down >= SECOND_ALERT_MINS get a
    # follow-up notification).
    currently_down: list[tuple[str, dict]] = []  # (ride_id, attraction)

    # ride_id → current operating wait, accumulated across all parks for
    # the post-loop plan-drift check (planned rides now vs prediction).
    current_waits: dict[str, int] = {}

    for park_key in PARK_KEYS:
        try:
            attractions = wait_times.fetch_live_data(park_key)
        except Exception as e:
            print(f"[poller] ERROR fetching {park_key}: {e}")
            continue

        print(f"[poller] {park_key}: {len(attractions)} attractions")
        subscribers = get_subscribers(park_key)
        now_dt = datetime.now(timezone.utc)
        now_iso = now_dt.isoformat()

        # Park-wide today_vs_forecast ratio, computed once per park
        # from the in-memory attractions list. Same shape as the MCP
        # planner's `_compute_load_vs_forecast` but operating on the
        # fresh upstream payload instead of DDB FORECAST# rows —
        # avoids a per-poll DDB read. Returns (None, 0) when the
        # park lacks enough qualifying forecasts to compute a
        # meaningful ratio; downstream LOW_VS_FORECAST check
        # short-circuits cleanly in that case.
        park_load_ratio, park_n_sampled = forecast_signal.compute_park_load_ratio(
            attractions, datetime.now(_EASTERN)
        )
        if park_load_ratio is not None:
            print(
                f"[poller] {park_key}: park_load_ratio={park_load_ratio} "
                f"(n={park_n_sampled} rides sampled)"
            )

        for attr in attractions:
            ride_id = attr["id"]
            new_status = attr["status"]
            new_wait = attr["wait_mins"]

            existing = db.get_ride(ride_id)
            old_status = existing["status"] if existing else None

            db.upsert_ride(attr)

            # Phase A2: persist this poll's forecast snapshot (when
            # upstream provided one) into a FORECAST# sub-row. Wrapped
            # so a forecast-side failure can never break the alert path
            # — a missed forecast is a rounding error against an
            # 8.8M-row historical baseline; a missed alert is a real
            # demo regression. Skip cleanly when the ride has no
            # forecast (DOWN rides, walk-up meets, transportation).
            if attr.get("forecast"):
                try:
                    db.record_forecast(ride_id, attr["last_seen"], attr["forecast"])
                except Exception as e:
                    print(f"[poller] forecast write failed for {attr['name']}: {e}")

            # M6-B Phase 1: persist raw per-poll wait observation for
            # operating rides. Mirrors the Pi's collection pattern in
            # DDB so the analytics aggregator can eventually source
            # from AWS. Only operating rides with a numeric wait —
            # DOWN rides + walk-ups + transportation don't carry
            # comparable wait values. Wrapped defensively for the same
            # reason as the forecast write above: a missed observation
            # is rounding-error scale; a broken alert path is not.
            if new_status == "OPERATING" and new_wait is not None:
                current_waits[ride_id] = new_wait
                try:
                    db.record_wait_observation(
                        ride_id=ride_id,
                        park_key=park_key,
                        wait_mins=new_wait,
                        polled_at=attr["last_seen"],
                    )
                except Exception as e:
                    print(f"[poller] wait observation write failed for {attr['name']}: {e}")

            # First time we've seen this ride — record state, no alert.
            if old_status is None:
                continue

            # Track down state regardless of alert fanout, so the
            # "back up" duration and "still down" sweep work even if
            # nobody was subscribed at the time it went down.
            if new_status == "DOWN":
                currently_down.append((ride_id, attr))

            # ── EARLIER LIGHTNING LANE (watch) ─────────────────────
            # Fire when a ride's LL return window moved earlier than the
            # prior poll. Recipients: the active-plan party for this ride
            # (always watched) PLUS park-subscribers who opted into
            # LL-watch on this ride (favorites, default-off). Any
            # improvement, no cooldown (per design); dedupe by Pushover
            # key so a plan+favorite overlap is one push, plan framing
            # winning. Park-hours gated like every other alert.
            # Held-LL precision: if the plan holds an LL for this ride,
            # the improvement is only useful when the available slot beats
            # the time held (an improvement to a slot still LATER than what
            # you hold is noise — the case Megan hit). No held LL → the
            # meaningful-improvement rule (_ll_became_earlier) stands.
            _held = held_ll_by_ride.get(ride_id)
            _ll_beats_held = True
            if _held:
                _avail = _parse_iso(attr.get("ll", {}).get("return_start"))
                _held_dt = _parse_iso(_held)
                _ll_beats_held = bool(_avail and _held_dt and _avail < _held_dt)
            if (
                alerts_allowed(park_key)
                and _ll_beats_held
                and _ll_became_earlier((existing or {}).get("ll"), attr.get("ll"))
            ):
                new_ll = attr["ll"]
                prior_ll = (existing or {}).get("ll") or {}
                # Plan party for this ride (by ride_id or lowercased name,
                # mirroring the DOWN/UP plan lookup). Keep each user's
                # plan_id so an in-plan recipient's /replan link targets it.
                plan_pid_by_uid: dict[str, str] = {}
                for keyname in (ride_id, attr["name"].lower()):
                    for u, pid in plan_ride_index.get(keyname, []):
                        plan_pid_by_uid.setdefault(u, pid)
                plan_users = set(plan_pid_by_uid)
                # Favoriters who opted in (park-subscribers only).
                watch_favs = {
                    s
                    for s in subscribers
                    if ride_id in get_ll_watched(s, park_key)
                }
                # Dedupe by Pushover key; in_plan sticky-True per key.
                ll_by_key: dict[str, tuple[str, bool]] = {}
                for uid in plan_users | watch_favs:
                    key = get_user_key(uid)
                    if not key:
                        continue
                    in_plan = uid in plan_users
                    prev = ll_by_key.get(key)
                    ll_by_key[key] = (uid, in_plan or bool(prev and prev[1]))
                for key, (uid, in_plan) in ll_by_key.items():
                    if notifier.alert_ll_earlier(
                        key,
                        ride_name=attr["name"],
                        park_name=attr["park_name"],
                        park_key=park_key,
                        new_return_start=new_ll["return_start"],
                        prior_return_start=prior_ll.get("return_start"),
                        in_plan=in_plan,
                        price=new_ll.get("price"),
                        plan_id=plan_pid_by_uid.get(uid),
                        ride_id=ride_id,
                    ):
                        total_alerts += 1

            # ── LOW WAIT (two baselines, shared cooldown) ──────────
            # Two independent signals share the COOLDOWN#LOW_WAIT row
            # so a ride gets at most one low-wait-class push per
            # window regardless of which baseline triggered:
            #
            #   • LOW_WAIT (historical) — current wait below the per-
            #     (ride, hour) half-typical threshold from
            #     baselines.json. Catches all-time anomalies.
            #   • LOW_VS_FORECAST (today-aware) — current wait beats
            #     today's forecast by a margin meaningful relative to
            #     park-wide load. Catches heavy-crowd-day opportunities
            #     LOW_WAIT misses because absolute waits stay above
            #     the half-typical floor. Designed 2026-05-12.
            #
            # Each gate is independent; the alert body adapts to
            # whichever signal(s) fired. Independent of status-change
            # detection — this is the only alert type that fires on
            # stable-state polls. Park-hours + cooldown still gate
            # the actual fanout.
            if (
                new_status == "OPERATING"
                and new_wait is not None
                and alerts_allowed(park_key)
                and not db.is_low_wait_alert_on_cooldown(ride_id)
            ):
                now_et = datetime.now(_EASTERN)

                # Historical baseline check
                threshold = _low_wait_threshold(ride_id, now_et.hour)
                historical_fire = (
                    threshold is not None and new_wait <= threshold
                )
                typical_for_msg = threshold * 2 if threshold else None

                # Forecast-aware baseline check
                forecast_wait = forecast_signal.find_forecast_for_hour(
                    attr.get("forecast"), now_et
                )
                forecast_fire = forecast_signal.should_fire_low_vs_forecast(
                    current_wait=new_wait,
                    forecast_wait=forecast_wait,
                    park_ratio=park_load_ratio,
                    rides_sampled=park_n_sampled,
                )

                if historical_fire or forecast_fire:
                    # Two alert sources can match the same user, same as
                    # the DOWN path: favoriting the ride generally, OR
                    # having it (still un-ridden) in TODAY's active plan.
                    # The plan-aware framing is more actionable ("jump to
                    # it now, it's cheaper than planned"), so it wins via
                    # the resolver. Plan targets come from the active-plan
                    # ride index, which only holds ride_sequence of ACTIVE
                    # plans inside their window — dormant plans, completed
                    # rides, and out-of-window hours never alert.
                    low_wait_kwargs = {
                        "ride_name": attr["name"],
                        "park_name": attr["park_name"],
                        "park_key": park_key,
                        "wait_mins": new_wait,
                        "typical_wait_mins": (
                            typical_for_msg if historical_fire else None
                        ),
                        "forecast_wait_mins": (
                            forecast_wait if forecast_fire else None
                        ),
                    }
                    favoriters = filter_to_favoriters(
                        subscribers, park_key, ride_id
                    )
                    plan_targets = db.lookup_plan_targets(
                        plan_ride_index, ride_id, attr["name"]
                    )
                    candidates: list[alert_routing.AlertCandidate] = []
                    for target_user, target_plan in plan_targets:
                        candidates.append(alert_routing.AlertCandidate(
                            user_id=target_user,
                            priority=alert_routing.PRIORITY_PLAN,
                            notifier_fn=notifier.alert_plan_low_wait,
                            kwargs={**low_wait_kwargs, "plan_id": target_plan,
                                    "ride_id": ride_id},
                        ))
                    for fav_user in favoriters:
                        candidates.append(alert_routing.AlertCandidate(
                            user_id=fav_user,
                            priority=alert_routing.PRIORITY_FAVORITE,
                            notifier_fn=notifier.alert_low_wait,
                            kwargs=dict(low_wait_kwargs),
                        ))

                    resolved = alert_routing.resolve_alert_recipients(candidates)
                    if resolved:
                        # Cooldown is set per-ride (not per-recipient)
                        # — same pattern as DOWN. Set it only when we
                        # actually fan out so a window with no
                        # recipients can still alert the next user who
                        # favorites/plans the ride.
                        db.mark_low_wait_alert_sent(ride_id)
                        # Log which baseline(s) tripped so post-hoc
                        # log analysis can audit false-positive rate
                        # per signal.
                        triggers = []
                        if historical_fire:
                            triggers.append(f"typical~{typical_for_msg}m")
                        if forecast_fire:
                            triggers.append(f"forecast={forecast_wait}m")
                        print(
                            f"[poller] {attr['name']} LOW WAIT "
                            f"({new_wait}m, {', '.join(triggers)}): "
                            f"{len(favoriters)} favoriters, "
                            f"{len(plan_targets)} plan targets → "
                            f"{len(resolved)} unique recipients"
                        )
                        # Dedupe by Pushover key (owner implicit + web
                        # opt-in under their sub = same key, one push).
                        for target_user, user_key, candidate in (
                            alert_routing.dedupe_resolved_by_key(
                                resolved, get_user_key
                            )
                        ):
                            if candidate.notifier_fn(user_key, **candidate.kwargs):
                                total_alerts += 1

            # No status change → nothing more to do for this ride.
            if new_status == old_status:
                continue

            total_changes += 1
            db.record_status_change(
                ride_id=ride_id,
                ride_name=attr["name"],
                park_name=attr["park_name"],
                park_key=park_key,
                old_status=old_status,
                new_status=new_status,
                wait_mins=new_wait,
                changed_at=now_iso,
            )

            # ── DOWN: just went out of service ─────────────────────
            if new_status == "DOWN":
                db.set_down_since(ride_id, now_dt)

                # Park-hours gate: still record the change above (so
                # analytics + DOWN_SINCE tracking work), but don't
                # send the alert if we're outside operating hours or
                # within the closing buffer.
                if not alerts_allowed(park_key):
                    continue

                # Cooldown check: don't re-alert if we already pinged
                # for this ride in the last DOWN_ALERT_COOLDOWN_SECS.
                # (Themeparks.wiki occasionally flaps a ride
                # OPERATING→DOWN→OPERATING within minutes.)
                if db.is_down_alert_on_cooldown(ride_id):
                    print(f"[poller] Skipping DOWN alert for {attr['name']} (cooldown)")
                    continue

                # Cooldown is set per-ride (not per-recipient) on
                # purpose: even if zero users get the alert today
                # (no one favorited this ride), we still want the
                # cooldown to prevent flap-induced spam if a user
                # adds the favorite mid-window. They'll catch the
                # next event.
                db.mark_down_alert_sent(ride_id)

                # Two alert sources can match the same user for one
                # DOWN event: favoriting the ride generally, OR having
                # it in TODAY's plan. The plan-aware alert is more
                # actionable (names the plan, prompts a re-sequence),
                # so it must win when both apply. Build candidates
                # from each source and let alert_routing pick.
                favoriters = filter_to_favoriters(subscribers, park_key, ride_id)
                plan_targets = db.lookup_plan_targets(
                    plan_ride_index, ride_id, attr["name"]
                )

                candidates: list[alert_routing.AlertCandidate] = []
                for target_user, target_plan in plan_targets:
                    candidates.append(alert_routing.AlertCandidate(
                        user_id=target_user,
                        priority=alert_routing.PRIORITY_PLAN,
                        notifier_fn=notifier.alert_plan_disruption,
                        kwargs={
                            "ride_name": attr["name"],
                            "park_name": attr["park_name"],
                            "park_key": park_key,
                            "disruption_type": "went_down",
                            "plan_id": target_plan,
                            "ride_id": ride_id,
                        },
                    ))
                for fav_user in favoriters:
                    candidates.append(alert_routing.AlertCandidate(
                        user_id=fav_user,
                        priority=alert_routing.PRIORITY_FAVORITE,
                        notifier_fn=notifier.alert_ride_down,
                        kwargs={
                            "ride_name": attr["name"],
                            "park_name": attr["park_name"],
                            "park_key": park_key,
                        },
                    ))

                resolved = alert_routing.resolve_alert_recipients(candidates)
                print(
                    f"[poller] {attr['name']} DOWN: {len(subscribers)} park subs, "
                    f"{len(favoriters)} favoriters, {len(plan_targets)} plan "
                    f"targets → {len(resolved)} unique recipients"
                )
                # Dedupe by Pushover key: the owner is implicit AND may
                # also be opted in under their sub via the web toggle —
                # same key, one push (see alert_routing docstring).
                for target_user, user_key, candidate in (
                    alert_routing.dedupe_resolved_by_key(resolved, get_user_key)
                ):
                    if candidate.notifier_fn(user_key, **candidate.kwargs):
                        total_alerts += 1

            # ── BACK UP: was DOWN, now OPERATING ───────────────────
            elif new_status == "OPERATING" and old_status == "DOWN":
                went_down = db.get_down_since(ride_id)
                actual_mins = None
                if went_down:
                    actual_mins = round((now_dt - went_down).total_seconds() / 60)
                db.clear_down_since(ride_id)

                # Park-hours gate also applies to "back up" alerts —
                # if we suppressed the DOWN alert at park-close, the
                # matching UP alert at park-open the next morning
                # would be confusing context-free noise.
                if not alerts_allowed(park_key):
                    continue

                # Cooldown gate: flap protection. themeparks.wiki
                # sometimes reports a ride OPERATING→DOWN→OPERATING
                # repeatedly within minutes. Without this, every UP
                # transition fires a fresh BACK UP push. We still
                # record the state transition (above) so DOWN_SINCE
                # is cleared correctly; we just skip the alert.
                if db.is_back_up_alert_on_cooldown(ride_id):
                    print(f"[poller] Skipping BACK UP alert for {attr['name']} (cooldown)")
                    continue

                # Set cooldown BEFORE fanning out, same pattern as
                # DOWN cooldown — even if no users get pinged today
                # (no favoriters, no plan watchers), we still want
                # the cooldown to prevent flap spam if a user adds
                # the favorite / plan mid-window.
                db.mark_back_up_alert_sent(ride_id)

                # NOTE (2026-06-17, deliberate — don't "fix"): a plan
                # watcher who ACTIVATED their plan after the ride went down
                # gets this BACK UP without ever having received the
                # matching DOWN (they weren't in the active set at
                # down-time). Accepted: it provides useful context ("a ride
                # in your plan had a hiccup but it's operational now") as
                # they head in. Suppressing it would need per-user
                # down-notified tracking — not worth the small noise it'd
                # remove.

                # Mirror of the DOWN path's resolver-based dispatch.
                # Plan-aware alert (priority 100) beats generic
                # favoriter alert (priority 50) when a user matches
                # both sources. See alert_routing.py for the rationale.
                favoriters = filter_to_favoriters(subscribers, park_key, ride_id)
                plan_targets = db.lookup_plan_targets(
                    plan_ride_index, ride_id, attr["name"]
                )

                candidates: list[alert_routing.AlertCandidate] = []
                for target_user, target_plan in plan_targets:
                    candidates.append(alert_routing.AlertCandidate(
                        user_id=target_user,
                        priority=alert_routing.PRIORITY_PLAN,
                        notifier_fn=notifier.alert_plan_disruption,
                        kwargs={
                            "ride_name": attr["name"],
                            "park_name": attr["park_name"],
                            "park_key": park_key,
                            "disruption_type": "back_up",
                            "plan_id": target_plan,
                            "wait_mins": new_wait,
                        },
                    ))
                for fav_user in favoriters:
                    candidates.append(alert_routing.AlertCandidate(
                        user_id=fav_user,
                        priority=alert_routing.PRIORITY_FAVORITE,
                        notifier_fn=notifier.alert_ride_up,
                        kwargs={
                            "ride_name": attr["name"],
                            "park_name": attr["park_name"],
                            "park_key": park_key,
                            "wait_mins": new_wait,
                            "actual_downtime_mins": actual_mins,
                        },
                    ))

                resolved = alert_routing.resolve_alert_recipients(candidates)
                print(
                    f"[poller] {attr['name']} BACK UP: {len(subscribers)} park subs, "
                    f"{len(favoriters)} favoriters, {len(plan_targets)} plan "
                    f"targets → {len(resolved)} unique recipients"
                )
                # Dedupe by Pushover key: the owner is implicit AND may
                # also be opted in under their sub via the web toggle —
                # same key, one push (see alert_routing docstring).
                for target_user, user_key, candidate in (
                    alert_routing.dedupe_resolved_by_key(resolved, get_user_key)
                ):
                    if candidate.notifier_fn(user_key, **candidate.kwargs):
                        total_alerts += 1

            # CLOSED transitions intentionally don't alert — too noisy
            # at park closing time.

    # ── Second alert sweep: rides down >= SECOND_ALERT_MINS ───────
    # Runs once per invocation after all parks processed.
    for ride_id, attr in currently_down:
        # Park-hours gate applies here too — no "still down" pings
        # at 11pm just because the ride went down at park-close.
        if not alerts_allowed(attr["park_key"]):
            continue
        went_down = db.get_down_since(ride_id)
        if not went_down:
            continue
        elapsed_mins = (datetime.now(timezone.utc) - went_down).total_seconds() / 60
        if elapsed_mins < SECOND_ALERT_MINS:
            continue

        # Separate cooldown key so the still-down alert doesn't collide
        # with the initial DOWN cooldown. Goes through the db helpers
        # (not an inline _table write) so it shares the ttl-aware cooldown
        # check — a best-effort-TTL-undeleted row must not silently
        # suppress a later second-alert.
        if db.is_still_down_alert_on_cooldown(ride_id):
            continue
        db.mark_still_down_alert_sent(ride_id, SECOND_ALERT_MINS * 60)

        subscribers = get_subscribers(attr["park_key"])
        favoriters = filter_to_favoriters(subscribers, attr["park_key"], ride_id)
        print(
            f"[poller] {attr['name']} STILL DOWN ({int(elapsed_mins)}m): "
            f"{len(subscribers)} park subs, {len(favoriters)} favoriters → alerting"
        )
        total_alerts += _fanout(
            favoriters, get_user_key,
            notifier.alert_still_down,
            ride_name=attr["name"],
            park_name=attr["park_name"],
            park_key=attr["park_key"],
            minutes_down=int(elapsed_mins),
        )

    # ── Plan-drift sweep: whole-plan "running lighter/heavier than
    # planned" nudge. One aggregated, heavily-cooldowned alert per plan
    # instead of per-ride low-wait spam on a drifting day. Dedupe
    # active_plans (per-recipient) down to one drift computation per plan.
    seen_drift_plans: set[str] = set()
    for plan in (active_plans if PLAN_DRIFT_ENABLED else []):
        plan_id = plan["plan_id"]
        if plan_id in seen_drift_plans:
            continue
        seen_drift_plans.add(plan_id)
        net, n = _compute_plan_drift(plan.get("rides") or [], current_waits)
        if n < 2 or abs(net) < PLAN_DRIFT_THRESHOLD_MIN:
            continue
        park_key = plan.get("park_key") or "magic_kingdom"
        park_name = PARK_NAMES.get(park_key, park_key.replace("_", " ").title())
        # Fan out to the plan's recipients (owner + subscribers), each
        # with their own per-(user, plan) cooldown + key dedup.
        seen_drift_keys: set[str] = set()
        for p in active_plans:
            if p["plan_id"] != plan_id:
                continue
            uid = p["user_id"]
            if db.is_plan_drift_on_cooldown(uid, plan_id):
                continue
            key = get_user_key(uid)
            if not key or key in seen_drift_keys:
                continue
            seen_drift_keys.add(key)
            db.mark_plan_drift_sent(uid, plan_id)
            if notifier.alert_plan_drift(
                key, park_name=park_name, park_key=park_key,
                net_minutes=net, plan_id=plan_id,
            ):
                total_alerts += 1

    elapsed = time.time() - started
    print(
        f"[poller] Done. {total_changes} status changes, "
        f"{total_alerts} alerts sent, {elapsed:.1f}s elapsed"
    )
    return {
        "status": "ok",
        "parks_polled": len(PARK_KEYS),
        "changes": total_changes,
        "alerts_sent": total_alerts,
        "elapsed_secs": round(elapsed, 1),
    }


def _fanout(subscribers: list[str], get_user_key, alert_fn, **kwargs) -> int:
    """Send the same alert to every subscriber. Returns count sent."""
    sent = 0
    for user_id in subscribers:
        user_key = get_user_key(user_id)
        if not user_key:
            print(f"[poller] No pushover_user_key for user {user_id} — skipping")
            continue
        if alert_fn(user_key, **kwargs):
            sent += 1
    return sent
