/**
 * Types + helpers for the M6 analytics page (Option C — frozen).
 *
 * The data ships as a static TS module at `web/src/data/analytics-snapshot.ts`,
 * generated by `tools/aggregate-analytics.py` from a SQLite snapshot of
 * the Pi's wait_history. No DDB or Lambda involvement on this layer —
 * Server Components import the snapshot directly. To refresh, re-snapshot
 * the Pi, re-run the aggregator, commit the regenerated TS file.
 *
 * If MM ever stops importing from the Pi and starts deriving its own
 * analytics from DDB, this file's read-shape stays the same; only the
 * source of `ANALYTICS_SNAPSHOT` changes.
 */

import { ANALYTICS_SNAPSHOT } from "@/data/analytics-snapshot";

import type { ParkKey } from "./parks";

export interface RideAnalytics {
  ride_id: string;
  ride_name: string;
  park_key: ParkKey;
  /** Total wait_history rows (all statuses). Sample-size sanity. */
  total_polls: number;
  /** Percentage of (OPERATING ∪ DOWN) polls that were DOWN. 0–100. */
  downtime_pct: number;
  /** Highest reported wait_mins seen while OPERATING. Null if always closed. */
  max_wait: number | null;
  /** Mean wait_mins while OPERATING. Null if no operating polls. */
  avg_wait: number | null;
  /** Avg wait_mins per hour-of-day (0-23, ET). Sparse if no data for an hour. */
  hourly_wait: { hour: number; wait: number }[];
  /** Downtime % per hour-of-day. Cells with <20 active polls are filtered out. */
  hourly_downtime: { hour: number; pct: number }[];
}

export interface HeatmapCell {
  /** 0-23, Eastern time. */
  hour: number;
  /** 0=Sunday … 6=Saturday (SQLite strftime('%w') convention). */
  dow: number;
  /** Avg wait_mins across rides at this (park, dow, hour). */
  wait: number;
  /** Underlying poll count — used for confidence checks if needed. */
  n: number;
}

export interface AnalyticsSnapshot {
  /** ISO timestamp the aggregator wrote this file. */
  generated_at: string;
  /** First and last polled_at values in the source data. ISO strings. */
  date_range: { start: string; end: string };
  /** Total wait_history rows the aggregations ran across. */
  total_polls: number;
  /** Per-ride breakdown, sorted by downtime % descending. */
  rides: RideAnalytics[];
  /** Per-park hour×dow heatmaps. Keyed by ParkKey. */
  heatmaps: Record<ParkKey, HeatmapCell[]>;
}

export function getAnalytics(): AnalyticsSnapshot {
  return ANALYTICS_SNAPSHOT;
}

export function getRidesForPark(parkKey: ParkKey): RideAnalytics[] {
  return ANALYTICS_SNAPSHOT.rides.filter((r) => r.park_key === parkKey);
}

export function getParkHeatmap(parkKey: ParkKey): HeatmapCell[] {
  return ANALYTICS_SNAPSHOT.heatmaps[parkKey] ?? [];
}

/**
 * "March 10 – May 6, 2026" from the ISO range. Intl handles the ordinal
 * suffixes via the locale; cross-year ranges aren't a concern at this
 * stage of the project (single Pi snapshot, single year).
 */
export function formatDateRange(startIso: string, endIso: string): string {
  const fmt = new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    timeZone: "America/New_York",
  });
  const yearFmt = new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    timeZone: "America/New_York",
  });
  const start = new Date(startIso);
  const end = new Date(endIso);
  return `${fmt.format(start)} – ${fmt.format(end)}, ${yearFmt.format(end)}`;
}

/** "1.2M" / "8,790,000" / "120" — short labels for big poll counts. */
export function formatPollCount(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 10_000) return `${Math.round(n / 1000)}K`;
  return n.toLocaleString("en-US");
}

/** Day-of-week labels — SQLite %w order (Sun-first). */
export const DOW_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
