// AUTO-GENERATED by tools/aggregate-analytics.py — do not edit by hand.
// Re-export of analytics-snapshot.json with the typed shape from
// @/lib/analytics applied. The .json file is the source of truth
// (read by Python tooling, e.g. the MCP server). The web app
// keeps importing `ANALYTICS_SNAPSHOT` from this module; only the
// internals changed.
//
// Regenerate by re-snapshotting the Pi and running:
//   python3 tools/aggregate-analytics.py
//
// 92 rides × hourly + per-park hour×day heatmaps,
// aggregated from 3,803,710 polls spanning
// 2026-03-10 → 2026-07-16.

import type { AnalyticsSnapshot } from "@/lib/analytics";
import data from "./analytics-snapshot.json";

export const ANALYTICS_SNAPSHOT = data as AnalyticsSnapshot;
