"""
Magic Monitor MCP server.

Exposes Magic Monitor's analytics + (eventually) live ride data as
tools an MCP client (Claude Desktop, Cline, agentic frameworks)
can invoke conversationally. Server speaks MCP over stdio so the
client launches it as a subprocess.

v2 — analytics-snapshot tools + short-wait baseline tool. All
read-only and offline; no AWS credentials needed. Live DDB tools
land in v3 once we wire boto3 + SSO refresh handling.

To run standalone for debugging:
    cd mcp && .venv/bin/python server.py
The server will block on stdio waiting for an MCP client to connect;
that's expected. Use the MCP Inspector for interactive testing:
    npx @modelcontextprotocol/inspector .venv/bin/python server.py
"""
import json
import os
from datetime import datetime, time, timedelta, timezone
from functools import lru_cache
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from mcp.server.fastmcp import FastMCP

# DDB region pinned to match the deployed stack (RUNBOOK Quick Reference).
# Profile is intentionally NOT hard-coded — boto3's default credential
# chain picks up `AWS_PROFILE=watchtower` from Claude Desktop's MCP env
# block, env vars on the user's shell, or the active SSO cache. That way
# the same code works for the project owner and any reviewer who points
# their own profile at the same account.
_DDB_REGION = os.environ.get("DISNEY_REGION", "us-east-2")
_DDB_TABLE = os.environ.get("DISNEY_TABLE_NAME", "DisneyData")

# Default AWS profile when AWS_PROFILE isn't set in the environment.
# Claude Desktop currently strips the `env` block from
# claude_desktop_config.json's mcpServers entries on quit/launch, so
# AWS_PROFILE often won't be present even if the config originally
# included it. Defaulting here keeps the server working without the
# user having to re-edit the config after every restart. The env var
# still wins when set — a reviewer pointing at a different account
# can `AWS_PROFILE=their-profile` without code changes.
_DDB_PROFILE = os.environ.get("AWS_PROFILE", "watchtower")

# Park-day boundary in Eastern time. Mirrors tools/aggregate-analytics.py
# so the live downtime tool agrees with the historical heatmap and
# down-cluster aggregations: a 1am Friday breakdown counts as
# "Thursday's park day," not Friday's. Disney World's parks span ET
# year-round; no per-park override needed.
_PARK_DAY_BOUNDARY_HOUR = 4
_EASTERN = ZoneInfo("America/New_York")
# HIST# row TTL in the poller. Tools that look further back than this
# will return empty results — make that explicit rather than silent.
_HIST_RETENTION_DAYS = 90

mcp = FastMCP("Magic Monitor")

# Data files. Both regenerated by tools/aggregate-analytics.py from
# the Pi-side SQLite snapshot. The MCP server reads them at first
# tool-call (lru_cache below) and holds them for the process
# lifetime — Claude Desktop keeps the server warm across calls in
# a single session, so paying the file-read cost once is right.
_ROOT = Path(__file__).resolve().parent.parent
_SNAPSHOT_PATH = _ROOT / "web" / "src" / "data" / "analytics-snapshot.json"
_BASELINES_PATH = _ROOT / "infra" / "lambda" / "poller" / "baselines.json"
_LOCATIONS_PATH = _ROOT / "web" / "src" / "data" / "attraction-locations.json"

# Walt Disney World coordinates (entrance plaza). Used to fetch a
# single weather forecast that's representative of all four parks —
# they're all within ~6km of each other so weather doesn't vary
# meaningfully between them at the planning resolution we care about.
_WDW_LAT = 28.3852
_WDW_LON = -81.5639

# SQLite-style day-of-week (Sun=0..Sat=6) — matches the heatmap data.
_DOW_NAMES = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
_DOW_INDEX = {name: i for i, name in enumerate(_DOW_NAMES)}

_PARK_KEYS = {"magic_kingdom", "epcot", "hollywood_studios", "animal_kingdom"}


@lru_cache(maxsize=1)
def _snapshot() -> dict[str, Any]:
    """Load the analytics snapshot once per process."""
    return json.loads(_SNAPSHOT_PATH.read_text())


@lru_cache(maxsize=1)
def _baselines() -> dict[str, Any]:
    """Load the short-wait alert thresholds once per process."""
    return json.loads(_BASELINES_PATH.read_text())


@lru_cache(maxsize=1)
def _locations() -> dict[str, dict[str, Any]]:
    """Load the lat/lon snapshot once per process.

    Generated by tools/fetch-attraction-locations.py from the
    themeparks.wiki entity endpoint. Keyed by ride_id, value has
    {name, park_key, lat, lon}. Locations are static — Space Mountain
    doesn't move — so re-run the script only when entity IDs change
    (rare, mostly during refurbs).
    """
    if not _LOCATIONS_PATH.exists():
        return {}
    return json.loads(_LOCATIONS_PATH.read_text())


@lru_cache(maxsize=1)
def _ddb_table():
    """Lazy-init the DDB table resource on first live-data tool call.

    Defers the boto3 import + session construction until a tool that
    actually needs DDB runs. Offline tools (analytics-snapshot readers)
    keep working even when AWS creds are unavailable, which keeps the
    MCP server itself usable for local demos that don't touch live
    data — for example, a portfolio walkthrough on a laptop with no
    SSO session.
    """
    import boto3  # local import: only paid when DDB is actually used
    session = boto3.Session(profile_name=_DDB_PROFILE, region_name=_DDB_REGION)
    return session.resource("dynamodb").Table(_DDB_TABLE)


def _convert_decimals(obj: Any) -> Any:
    """Recursively convert boto3 Decimals to int/float for JSON-friendly output.

    DynamoDB returns numbers as `decimal.Decimal` to preserve precision.
    MCP tool returns get serialized to JSON for the client, and JSON
    has no Decimal type — without this conversion the MCP runtime fails
    or surfaces opaque type errors. We convert back to int when the value
    is whole (matches our write shape) and float otherwise.
    """
    from decimal import Decimal
    if isinstance(obj, Decimal):
        return int(obj) if obj == obj.to_integral_value() else float(obj)
    if isinstance(obj, dict):
        return {k: _convert_decimals(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_convert_decimals(v) for v in obj]
    return obj


def _normalize_park(park: str) -> str:
    """Accept 'Magic Kingdom' / 'magic_kingdom' / 'MK' / 'mk', return canonical key.

    Raises ValueError on unknown input so the MCP client surfaces a
    clear message instead of an empty result.
    """
    p = park.strip().lower().replace(" ", "_").replace("-", "_")
    if p in _PARK_KEYS:
        return p
    aliases = {
        "mk": "magic_kingdom",
        "magickingdom": "magic_kingdom",
        "ep": "epcot",
        "hs": "hollywood_studios",
        "dhs": "hollywood_studios",
        "hollywoodstudios": "hollywood_studios",
        "ak": "animal_kingdom",
        "animalkingdom": "animal_kingdom",
    }
    if p.replace("_", "") in aliases:
        return aliases[p.replace("_", "")]
    raise ValueError(
        f"Unknown park '{park}'. Use one of: "
        f"{', '.join(sorted(_PARK_KEYS))} (or aliases like MK, EP, HS, AK)."
    )


def _find_ride(ride_name: str) -> dict[str, Any]:
    """Resolve a free-text ride name to a snapshot record (substring match).

    Returns the first ride whose name contains the query (case-
    insensitive). Raises ValueError if nothing matches — better to
    fail loudly than to silently match a wrong ride.
    """
    q = ride_name.strip().lower()
    if not q:
        raise ValueError("ride_name cannot be empty")
    rides = _snapshot()["rides"]
    for r in rides:
        if q in r["ride_name"].lower():
            return r
    raise ValueError(
        f"No ride matching '{ride_name}'. "
        f"Use find_rides_matching to list rides by criteria."
    )


# ───────────────────────────── tools ─────────────────────────────


@mcp.tool()
def hello_magic_monitor() -> str:
    """Sanity-check that the Magic Monitor MCP server is loaded and reachable.

    Returns a short greeting confirming the wiring works.
    """
    return (
        "Hello from Magic Monitor — MCP wiring works. "
        "Available tools: get_park_heatmap, get_ride_analytics, "
        "get_ride_dow_pattern, get_ride_down_clusters, "
        "get_short_wait_baseline, get_ride_forecast, "
        "get_live_ride_status, get_park_live_status, "
        "get_ride_downtime_today, get_planning_context, "
        "find_rides_matching."
    )


@mcp.tool()
def get_park_heatmap(park: str, day_of_week: str | None = None) -> dict[str, Any]:
    """Return the wait-time heatmap cells for one park.

    The heatmap aggregates millions of historical poll snapshots into
    average wait minutes by day-of-week × hour-of-day, in Eastern time.
    Hours 0-3 (12-3am) are attributed to the previous day's row to
    handle late-night events. Cells with fewer than 20 active polls
    are omitted (treated as "park closed at this hour").

    Args:
        park: Park key or human-readable name. Accepts 'magic_kingdom',
            'Magic Kingdom', 'MK', etc.
        day_of_week: Optional. Filter to one day. Accepts 'monday',
            'tuesday', etc. If omitted, returns all 7 days.

    Returns:
        Dict with park key, optional day filter, and a list of cells
        each containing hour (0-23 ET), dow (0=Sun..6=Sat), avg wait
        in minutes, and the underlying poll count.
    """
    park_key = _normalize_park(park)
    cells = _snapshot()["heatmaps"].get(park_key, [])
    dow_filter: int | None = None
    if day_of_week is not None:
        dow_filter = _DOW_INDEX.get(day_of_week.strip().lower())
        if dow_filter is None:
            raise ValueError(
                f"Unknown day_of_week '{day_of_week}'. "
                f"Use one of: {', '.join(_DOW_NAMES)}."
            )
        cells = [c for c in cells if c["dow"] == dow_filter]
    return {
        "park": park_key,
        "day_of_week": _DOW_NAMES[dow_filter] if dow_filter is not None else None,
        "cell_count": len(cells),
        "cells": cells,
    }


@mcp.tool()
def get_ride_analytics(ride_name: str) -> dict[str, Any]:
    """Return analytics for one ride (downtime %, hourly waits, etc.).

    Substring match on ride_name (case-insensitive); returns the
    first matching ride. Use find_rides_matching to discover ride
    names by criteria.

    Args:
        ride_name: Free-text ride name. 'big thunder' matches
            'Big Thunder Mountain Railroad'.

    Returns:
        Dict with ride_name, park_key, total_polls, downtime_pct
        (0-100), max_wait minutes, avg_wait minutes, hourly_wait
        (one entry per ET hour-of-day with avg wait in minutes), and
        hourly_downtime (one entry per ET hour-of-day with downtime %).
    """
    return _find_ride(ride_name)


@mcp.tool()
def get_short_wait_baseline(
    ride_name: str, hour: int | None = None
) -> dict[str, Any]:
    """Return the per-hour short-wait alert thresholds for a ride.

    Magic Monitor's poller fires a Pushover notification when a ride's
    current wait drops below this threshold (and the ride is operating,
    and the user has favorited it, etc.). Thresholds are computed from
    historical wait_history as min(30, 0.5 × typical), and are only
    emitted when typical waits at that hour clear 25 minutes — there's
    no point alerting on rides whose typical wait is already short.

    Args:
        ride_name: Free-text ride name. Substring match.
        hour: Optional. One ET hour-of-day (0-23). If omitted, returns
            the threshold for every hour the ride has one for.

    Returns:
        Dict with ride_name, ride_id, an explanation of the metric,
        and either a single threshold (if `hour` given) or a map
        of hour -> threshold. Returns an empty thresholds map if the
        ride has no alertable hours (typical wait too low everywhere).
    """
    ride = _find_ride(ride_name)
    rid = ride["ride_id"]
    thresholds = _baselines().get("rides", {}).get(rid, {})
    info: dict[str, Any] = {
        "ride_name": ride["ride_name"],
        "ride_id": rid,
        "explanation": (
            "Wait minutes below this threshold (when status=OPERATING) "
            "fire a SHORT_WAIT alert. Threshold = min(30, 0.5 × typical) "
            "for hours where typical wait ≥ 25 min."
        ),
    }
    if hour is not None:
        if not 0 <= hour <= 23:
            raise ValueError(f"hour must be 0-23, got {hour}")
        info["hour"] = hour
        info["threshold_minutes"] = thresholds.get(str(hour))
    else:
        info["thresholds_by_hour"] = {int(h): t for h, t in sorted(
            thresholds.items(), key=lambda kv: int(kv[0])
        )}
    return info


@mcp.tool()
def get_ride_dow_pattern(
    ride_name: str, day_of_week: str | None = None
) -> dict[str, Any]:
    """Return per-(day-of-week, hour) wait + downtime cells for one ride.

    Use this when you need to answer 'how does X behave on Sundays?' /
    'is Pirates worse on Mondays vs Saturdays?' / 'when's the best
    Tuesday-evening window for Test Track?' type questions. Cells with
    fewer than 20 active polls in the historical data are omitted, so
    rides with thin Sunday-morning samples show only the buckets
    where the answer is meaningful.

    Same park-day-boundary rule as the park heatmap: 12-3am polls are
    attributed to the previous day's row. A 1am Friday poll counts
    against Thursday's Friday-late-night experience, not Friday's
    pre-dawn.

    Args:
        ride_name: Substring match (case-insensitive). 'big thunder'
            matches 'Big Thunder Mountain Railroad'.
        day_of_week: Optional. Filter to one day. Accepts 'monday',
            'tuesday', etc. If omitted, returns cells for all 7 days.

    Returns:
        Dict with ride_name, ride_id, the optional day_of_week filter
        echoed back, the cell count, and an array of cells each with
        dow (0=Sun..6=Sat), hour (0-23 ET), downtime_pct, n_active,
        and wait (operating-only avg, omitted when zero operating
        polls in that bucket).
    """
    ride = _find_ride(ride_name)
    cells = ride.get("dow_hourly", [])
    dow_filter: int | None = None
    if day_of_week is not None:
        dow_filter = _DOW_INDEX.get(day_of_week.strip().lower())
        if dow_filter is None:
            raise ValueError(
                f"Unknown day_of_week '{day_of_week}'. "
                f"Use one of: {', '.join(_DOW_NAMES)}."
            )
        cells = [c for c in cells if c["dow"] == dow_filter]
    return {
        "ride_name": ride["ride_name"],
        "ride_id": ride["ride_id"],
        "day_of_week": _DOW_NAMES[dow_filter] if dow_filter is not None else None,
        "cell_count": len(cells),
        "cells": cells,
    }


@mcp.tool()
def get_ride_down_clusters(ride_name: str) -> dict[str, Any]:
    """Return the contiguous DOWN runs ('clusters') detected for a ride.

    Use this to investigate whether a ride's downtime looks 'structural'
    (long sustained DOWN periods recurring at consistent times) or
    'flap-style' (many short DOWN events scattered throughout the data
    window). High clustering at consistent (dow, hour) IS a signal,
    not a diagnosis — possible causes include scheduled maintenance,
    inspections, multi-week mechanical issues right before refurb, or
    upstream API quirks. The data alone can't determine which.

    Companion to get_ride_dow_pattern: each cell's
    `recurring_down_fraction` tells you what fraction of that bucket's
    DOWN polls were part of a long cluster.

    Args:
        ride_name: Substring match (case-insensitive).

    Returns:
        Dict with ride_name, ride_id, cluster_count, and a list of
        clusters each with start_ts, end_ts, duration_minutes,
        poll_count, start_hour (0-23 ET), and start_dow (0=Sun..6=Sat,
        park-day-shifted). Includes summary stats: total downtime
        across clusters, count of long clusters (≥2h), and the most
        common (dow, hour) start pair if one exists.
    """
    ride = _find_ride(ride_name)
    clusters = ride.get("down_clusters", [])

    # Compute simple summary stats so the model has a header it can
    # reason about without iterating the full cluster list itself.
    total_downtime = sum(c["duration_minutes"] for c in clusters)
    long_count = sum(1 for c in clusters if c["duration_minutes"] >= 120)
    # Most common (dow, hour) start — recurring-time signal.
    from collections import Counter
    start_counter = Counter(
        (c["start_dow"], c["start_hour"]) for c in clusters
    )
    most_common_start = None
    if start_counter:
        (top_dow, top_hour), top_n = start_counter.most_common(1)[0]
        if top_n >= 2:  # only meaningful if it repeats
            most_common_start = {
                "dow": top_dow,
                "hour": top_hour,
                "occurrences": top_n,
                "out_of_total_clusters": len(clusters),
            }
    return {
        "ride_name": ride["ride_name"],
        "ride_id": ride["ride_id"],
        "cluster_count": len(clusters),
        "long_cluster_count": long_count,
        "total_downtime_minutes": total_downtime,
        "most_common_start": most_common_start,
        "clusters": clusters,
    }


@mcp.tool()
def get_ride_forecast(ride_name: str) -> dict[str, Any]:
    """Return the most recent themeparks.wiki forecast for a ride.

    Live tool — reads the latest FORECAST# row from DynamoDB. Forecasts
    are upstream's hourly wait-time predictions covering current-hour
    through park close (~14 entries early in the day, fewer as it
    progresses). The poller captures one forecast snapshot per ride
    per 2-min poll and TTLs them after 7 days.

    Use this to answer 'how busy is Space Mountain expected to get
    later today?' / 'will the Test Track wait stay this short?' /
    'when does the system think Big Thunder peaks today?' Pair with
    get_ride_analytics for "expected today vs typical for this hour."

    Forecasts are absent for: DOWN rides, walk-up character meets,
    no-queue attractions (Main Street Vehicles, the Railroad), and
    some shows. The tool returns a clear `forecast_available: false`
    response in those cases, with the ride's `last_forecast_at` (when
    available) so you can answer 'when did Space Mountain stop having
    a forecast?'

    Args:
        ride_name: Substring match (case-insensitive). 'space mountain'
            matches 'Space Mountain'.

    Returns:
        Dict with ride_name, ride_id, polled_at (UTC iso), forecast
        (list of {time, wait_mins, percentage}). On absence: ride_name,
        ride_id, forecast_available=false, last_forecast_at (or null).
        On AWS auth failure: a clear error_hint pointing at SSO refresh.
    """
    ride = _find_ride(ride_name)
    rid = ride["ride_id"]

    try:
        table = _ddb_table()
        # Query the FORECAST# range for this ride, descending, take 1.
        # Pure key-condition (no FilterExpression) — boto3 begins_with
        # over an SK range is a single index walk. Limit=1 means we
        # walk one key and stop.
        resp = table.query(
            KeyConditionExpression="PK = :pk AND begins_with(SK, :sk)",
            ExpressionAttributeValues={
                ":pk": f"RIDE#{rid}",
                ":sk": "FORECAST#",
            },
            ScanIndexForward=False,
            Limit=1,
        )
    except Exception as e:
        err = _aws_error_payload(e)
        if err is not None:
            return {"ride_name": ride["ride_name"], "ride_id": rid, **err}
        return {
            "ride_name": ride["ride_name"],
            "ride_id": rid,
            "error": "DynamoDB query failed",
            "error_message": str(e),
        }

    items = resp.get("Items", [])
    if not items:
        # No forecast row found. Try to surface the cheap last-seen
        # signal we keep on the STATE row so the model can answer
        # "when did Space Mountain last have a forecast?" without a
        # second query loop.
        state_resp = table.get_item(Key={"PK": f"RIDE#{rid}", "SK": "STATE"})
        state = state_resp.get("Item") or {}
        return {
            "ride_name": ride["ride_name"],
            "ride_id": rid,
            "forecast_available": False,
            "last_forecast_at": state.get("last_forecast_at"),
            "current_status": state.get("status"),
            "explanation": (
                "No forecast in DynamoDB for this ride. Common reasons: "
                "ride is DOWN, walk-up attraction with no queue, or "
                "the upstream API isn't predicting it today. "
                "If last_forecast_at is set, that's when we last saw "
                "one — the gap is itself a signal worth investigating."
            ),
        }

    item = _convert_decimals(items[0])
    return {
        "ride_name": ride["ride_name"],
        "ride_id": rid,
        "polled_at": item.get("polled_at"),
        "forecast_available": True,
        "forecast_entries": len(item.get("forecast", [])),
        "forecast": item.get("forecast", []),
    }


def _aws_error_payload(e: Exception) -> dict[str, Any] | None:
    """If `e` is a recognizable AWS-auth failure, return a friendly
    error dict for the tool to surface. Otherwise return None so the
    caller can re-raise or wrap with its own context.

    Centralized so all live-DDB tools surface the same `aws sso login`
    hint instead of opaque tracebacks. Personal-dev SSO expiry is by
    far the most common failure mode here.
    """
    msg = str(e)
    # Token expiry (SSO refresh case) — friendly path:
    if "Token has expired" in msg or "ExpiredToken" in msg:
        return {
            "error": "AWS credentials expired",
            "error_hint": "Run `aws sso login --profile watchtower` and retry.",
        }
    # Invalid creds (different from expiry) — usually means boto3 picked
    # up the wrong profile entirely, e.g. a stale [default] in
    # ~/.aws/credentials when AWS_PROFILE wasn't set in the MCP env.
    # DynamoDB surfaces this as UnrecognizedClientException; STS as
    # InvalidClientTokenId; same root cause.
    if "InvalidClientTokenId" in msg or "UnrecognizedClientException" in msg:
        return {
            "error": "AWS credentials not recognized",
            "error_hint": (
                "boto3 is hitting AWS with credentials that aren't valid "
                "for this account. Most likely the MCP env doesn't set "
                "AWS_PROFILE=watchtower and boto3 is falling back to a "
                "stale [default] profile. Add "
                '`\"env\": {\"AWS_PROFILE\": \"watchtower\"}` '
                "to the magic-monitor block in claude_desktop_config.json "
                "and restart Claude Desktop."
            ),
        }
    return None


@mcp.tool()
def get_live_ride_status(ride_name: str) -> dict[str, Any]:
    """Return the most recent live status of a single ride.

    Live tool — GetItem on the RIDE#<id>/STATE row written by the
    poller every 2 minutes. Use this when the question is about ONE
    ride: 'is Space Mountain operating right now?' / 'what's the
    current wait for Big Thunder?' / 'when did this ride last update?'

    For park-wide queries ('what's down at Magic Kingdom?') use
    `get_park_live_status` instead — it's a single Scan vs N GetItems.

    IMPORTANT: how to read the response when status="DOWN":
    - `down_since` + `down_duration_mins` = how long this current DOWN
      has been going (right now).
    - `typical_down_cluster_mins` = median historical cluster duration
      for this ride (from the snapshot). `historical_cluster_count`
      tells you how many past clusters that median was computed from
      — small samples mean a noisy estimate.
    - `cluster_progress_pct` = current duration as a percentage of the
      historical median. <50% → probably still early, plan for more
      downtime. ~80-120% → could come back any minute. >>150% → this
      DOWN is unusually long, possibly a structural issue today.
    - `ll` is the LIGHTNING LANE OFFER currently being sold by Disney.
      `ll.return_start` is the time on the LL ticket — NOT a prediction
      of when the ride will be operating again. Disney sometimes keeps
      offering LL slots on a DOWN ride (betting on quick recovery, or
      the queue system has stale state). Do not infer "ride will be
      back at X PM" from `ll.return_start = X PM`. They are unrelated
      systems.

    Args:
        ride_name: Substring match (case-insensitive). 'space mountain'
            matches 'Space Mountain'.

    Returns:
        Dict with ride_name, ride_id, status, wait_mins, park_name,
        last_seen (UTC iso), last_forecast_at (when present), and
        Lightning Lane info when offered. When status="DOWN", also
        includes `down_since` (UTC iso) and `down_duration_mins`. On
        absence (ride exists in the historical snapshot but the poller
        hasn't seen it yet, e.g. a brand-new attraction):
        `live_state_available: false`. On AWS auth failure: a clear
        error_hint pointing at SSO refresh.
    """
    ride = _find_ride(ride_name)
    rid = ride["ride_id"]

    try:
        table = _ddb_table()
        resp = table.get_item(Key={"PK": f"RIDE#{rid}", "SK": "STATE"})
    except Exception as e:
        err = _aws_error_payload(e)
        if err is not None:
            return {"ride_name": ride["ride_name"], "ride_id": rid, **err}
        return {
            "ride_name": ride["ride_name"],
            "ride_id": rid,
            "error": "DynamoDB read failed",
            "error_message": str(e),
        }

    item = resp.get("Item")
    if not item:
        return {
            "ride_name": ride["ride_name"],
            "ride_id": rid,
            "live_state_available": False,
            "explanation": (
                "This ride exists in the historical analytics snapshot "
                "but no STATE row is in DynamoDB yet. The poller writes "
                "STATE on every 2-min cycle, so a missing row usually "
                "means the upstream API hasn't returned this attraction "
                "in any recent poll (could be brand-new or temporarily "
                "removed from /live)."
            ),
        }

    item = _convert_decimals(item)
    response: dict[str, Any] = {
        "ride_name": item.get("name") or ride["ride_name"],
        "ride_id": rid,
        "park_key": item.get("park_key"),
        "park_name": item.get("park_name"),
        "status": item.get("status"),
        "wait_mins": item.get("wait_mins"),
        "ll": item.get("ll"),
        "last_seen": item.get("last_seen"),
        "last_forecast_at": item.get("last_forecast_at"),
        "live_state_available": True,
    }

    # When the ride is currently DOWN, enrich with both the current
    # down duration AND the ride's historical-typical cluster length,
    # so the planner can reason about progress through the cluster
    # ("16 min in vs ~40 min typical → maybe 20 more") instead of
    # guessing from the (unrelated) LL offer.
    if item.get("status") == "DOWN":
        try:
            ds_resp = table.get_item(
                Key={"PK": f"RIDE#{rid}", "SK": "DOWN_SINCE"}
            )
            ds_item = ds_resp.get("Item")
            if ds_item and ds_item.get("down_since"):
                down_since_iso = ds_item["down_since"]
                response["down_since"] = down_since_iso
                # Compute duration from the DOWN_SINCE timestamp to now.
                # Wrapped so a parse failure doesn't drop the field.
                try:
                    down_dt = datetime.fromisoformat(down_since_iso)
                    elapsed = datetime.now(timezone.utc) - down_dt
                    response["down_duration_mins"] = round(
                        elapsed.total_seconds() / 60, 1
                    )
                except ValueError:
                    pass
        except Exception:
            # Failing to fetch DOWN_SINCE shouldn't fail the whole tool.
            # Status + timestamps are still useful without it.
            pass

        # Pull historical-typical cluster duration from the snapshot.
        # Median is robust to long-refurb outliers that would skew a
        # mean; if a ride has only a handful of clusters we still
        # surface the median because it's what we have.
        clusters = ride.get("down_clusters", [])
        if clusters:
            durations = sorted(
                c["duration_minutes"] for c in clusters
                if isinstance(c.get("duration_minutes"), (int, float))
            )
            if durations:
                mid = len(durations) // 2
                if len(durations) % 2 == 1:
                    median = durations[mid]
                else:
                    median = (durations[mid - 1] + durations[mid]) / 2
                response["typical_down_cluster_mins"] = round(median, 1)
                response["historical_cluster_count"] = len(durations)
                # Only emit a progress signal when we have both halves
                # of the comparison and it's meaningful.
                cur = response.get("down_duration_mins")
                if cur is not None and median > 0:
                    response["cluster_progress_pct"] = round(
                        100.0 * cur / median, 1
                    )

    return response


@mcp.tool()
def get_park_live_status(
    park: str, status_filter: str | None = None
) -> dict[str, Any]:
    """Return the current live status of every ride in one park.

    Live tool — Scan with FilterExpression on the DDB table. Use this
    when the question is about a park or a status across rides:
    'what's down at Magic Kingdom?' / 'which EPCOT rides have waits
    over 60 min?' / 'is anything operating at Animal Kingdom right now?'

    Returns rides sorted DOWN-first, then OPERATING by descending wait,
    then CLOSED/REFURBISHMENT — same order the live web UI uses so
    the model's response matches what a user sees on
    magicmonitor.megillini.dev.

    Implementation note (interview-relevant): this is a Scan + filter
    rather than a Query against a GSI on park_key. At MM's scale (~88
    rides total across all parks), the entire STATE corpus fits well
    within DynamoDB's 1MB scan page, so a single round trip beats the
    GSI's storage + write-amplification cost. A production scale-out
    (thousands of attractions, multi-tenant) would warrant the GSI.

    Args:
        park: Park key or human name. Accepts 'magic_kingdom',
            'Magic Kingdom', 'MK', etc. (See _normalize_park aliases.)
        status_filter: Optional. One of 'OPERATING', 'DOWN', 'CLOSED',
            'REFURBISHMENT'. Case-insensitive.

    Returns:
        Dict with park, optional status_filter echoed back, count of
        rides matched, and a list of rides each with ride_id, name,
        status, wait_mins, last_seen. On AWS auth failure: a clear
        error_hint pointing at SSO refresh.
    """
    park_key = _normalize_park(park)
    valid_statuses = {"OPERATING", "DOWN", "CLOSED", "REFURBISHMENT"}
    status_norm: str | None = None
    if status_filter is not None:
        status_norm = status_filter.strip().upper()
        if status_norm not in valid_statuses:
            raise ValueError(
                f"Unknown status_filter '{status_filter}'. "
                f"Use one of: {', '.join(sorted(valid_statuses))}."
            )

    try:
        table = _ddb_table()
        # Scan all STATE rows for this park. begins_with on PK isn't
        # supported by Scan (PK isn't an index here), but FilterExpression
        # on park_key + SK works and at our scale fits in one page.
        # Pagination defensively: if MM ever grows past 1MB of STATE
        # rows we'll see truncation rather than silently dropping rides.
        items: list[dict] = []
        scan_kwargs = {
            "FilterExpression": "SK = :sk AND park_key = :pk",
            "ExpressionAttributeValues": {":sk": "STATE", ":pk": park_key},
        }
        while True:
            resp = table.scan(**scan_kwargs)
            items.extend(resp.get("Items", []))
            if "LastEvaluatedKey" not in resp:
                break
            scan_kwargs["ExclusiveStartKey"] = resp["LastEvaluatedKey"]
    except Exception as e:
        err = _aws_error_payload(e)
        if err is not None:
            return {"park": park_key, **err}
        return {
            "park": park_key,
            "error": "DynamoDB scan failed",
            "error_message": str(e),
        }

    items = _convert_decimals(items)
    if status_norm is not None:
        items = [r for r in items if r.get("status") == status_norm]

    # Sort DOWN-first, then OPERATING desc-by-wait, then CLOSED last —
    # mirrors the web UI's ordering so the LLM's response feels
    # consistent with what someone sees on the live site.
    status_rank = {"DOWN": 0, "REFURBISHMENT": 1, "OPERATING": 2, "CLOSED": 3}
    def _sort_key(r: dict) -> tuple:
        rank = status_rank.get(r.get("status", ""), 99)
        # Negative wait so OPERATING rides sort by descending wait
        # (longest line first — what guests usually care about).
        wait = r.get("wait_mins")
        return (rank, -(wait if isinstance(wait, (int, float)) else -1))
    items.sort(key=_sort_key)

    return {
        "park": park_key,
        "status_filter": status_norm,
        "count": len(items),
        "rides": [
            {
                "ride_id": r.get("ride_id"),
                "name": r.get("name"),
                "status": r.get("status"),
                "wait_mins": r.get("wait_mins"),
                "last_seen": r.get("last_seen"),
            }
            for r in items
        ],
    }


def _park_day_window_utc(days_back: int) -> tuple[datetime, datetime, str]:
    """Return [start, end_inclusive] UTC datetimes covering one park-day.

    Park-days run 4am ET to 4am ET (next calendar day). A 1am Friday
    breakdown belongs to Thursday's park-day — matches the historical
    analytics convention in tools/aggregate-analytics.py exactly, so
    "today's down count" stays consistent with the live heatmap that
    the model can also pull via get_park_heatmap.

    `end_inclusive` is shifted back by 1 microsecond from the next
    park-day's start so DynamoDB BETWEEN over HIST# SKs is a clean
    half-open interval — a transition recorded at exactly the next
    park-day's 4am-ET-rendered-as-UTC won't double-count.
    """
    now_et = datetime.now(_EASTERN)
    target_date = (now_et - timedelta(days=days_back)).date()
    start_et = datetime.combine(
        target_date, time(_PARK_DAY_BOUNDARY_HOUR, 0), tzinfo=_EASTERN
    )
    end_et = start_et + timedelta(days=1) - timedelta(microseconds=1)
    return (
        start_et.astimezone(timezone.utc),
        end_et.astimezone(timezone.utc),
        target_date.isoformat(),
    )


@mcp.tool()
def get_ride_downtime_today(
    ride_name: str, days_back: int = 0
) -> dict[str, Any]:
    """Count how many times a ride went DOWN during one park-day.

    Live tool — Queries the RIDE#<id>/HIST#<ts> sub-rows the poller
    writes on every status transition. Returns each DOWN incident
    that *started* during the park-day window, plus how many
    DOWN→OPERATING recoveries fell in the same window.

    "Park-day" matches the analytics convention exactly: 4am ET to
    4am ET (next calendar day). A 12-3am poll attributes to the
    previous park-day's row. So "Big Thunder broke down 3 times
    today" is consistent across this tool, the heatmap, and the
    DOWN-cluster historical aggregation.

    Use this for: 'how many times has Big Thunder been down today?'
    'has Test Track had any breakdowns this morning?' 'pull yesterday's
    Pirates of the Caribbean downtime — was it that bad?'

    Args:
        ride_name: Substring match (case-insensitive). 'big thunder'
            matches 'Big Thunder Mountain Railroad'.
        days_back: 0 = today (default), 1 = yesterday, etc. Capped
            at 90 (HIST# rows TTL after 90 days; older queries return
            empty without explanation otherwise).

    Returns:
        Dict with ride_name, ride_id, park_day (ISO date), down_count,
        recovery_count, total_transitions (any status change in the
        window — useful for spotting flap), the down incidents (each
        with went_down_at + wait_at_breakdown), and an is_partial_day
        flag when the park-day is still in progress (i.e., days_back=0
        before 4am ET tomorrow). On AWS auth failure: a clear
        error_hint pointing at SSO refresh.
    """
    if days_back < 0:
        raise ValueError("days_back must be >= 0 (0 = today, 1 = yesterday)")
    if days_back > _HIST_RETENTION_DAYS:
        raise ValueError(
            f"HIST rows TTL after {_HIST_RETENTION_DAYS} days; "
            f"days_back={days_back} would return empty. "
            f"For older windows use the historical analytics snapshot "
            f"(get_ride_down_clusters)."
        )

    ride = _find_ride(ride_name)
    rid = ride["ride_id"]
    window_start_utc, window_end_utc, park_day = _park_day_window_utc(days_back)

    try:
        table = _ddb_table()
        # Query HIST# range with a SK BETWEEN. UTC ISO strings sort
        # lexicographically, so the BETWEEN cleanly bounds the window.
        # Defensively paginate even though one ride's transitions in
        # one park-day fit in a single page at any plausible volume.
        items: list[dict] = []
        sk_lo = f"HIST#{window_start_utc.isoformat()}"
        sk_hi = f"HIST#{window_end_utc.isoformat()}"
        kwargs = {
            "KeyConditionExpression": "PK = :pk AND SK BETWEEN :lo AND :hi",
            "ExpressionAttributeValues": {
                ":pk": f"RIDE#{rid}",
                ":lo": sk_lo,
                ":hi": sk_hi,
            },
        }
        while True:
            resp = table.query(**kwargs)
            items.extend(resp.get("Items", []))
            if "LastEvaluatedKey" not in resp:
                break
            kwargs["ExclusiveStartKey"] = resp["LastEvaluatedKey"]
    except Exception as e:
        err = _aws_error_payload(e)
        if err is not None:
            return {"ride_name": ride["ride_name"], "ride_id": rid, **err}
        return {
            "ride_name": ride["ride_name"],
            "ride_id": rid,
            "error": "DynamoDB query failed",
            "error_message": str(e),
        }

    items = _convert_decimals(items)
    down_events = [i for i in items if i.get("new_status") == "DOWN"]
    recoveries = [
        i for i in items
        if i.get("old_status") == "DOWN" and i.get("new_status") == "OPERATING"
    ]

    return {
        "ride_name": ride["ride_name"],
        "ride_id": rid,
        "park_day": park_day,
        "park_day_window_utc": {
            "start": window_start_utc.isoformat(),
            "end_inclusive": window_end_utc.isoformat(),
        },
        "is_partial_day": days_back == 0,
        "down_count": len(down_events),
        "recovery_count": len(recoveries),
        "total_transitions": len(items),
        "down_incidents": [
            {
                "went_down_at": e.get("changed_at"),
                "wait_at_breakdown": e.get("wait_mins"),
            }
            for e in down_events
        ],
    }


def _fetch_park_hours_today(park_key: str) -> dict[str, Any] | None:
    """Fetch today's open/close window for a park from themeparks.wiki.

    Mirrors the poller's fetch_park_hours logic so the planning tool
    sees the same hours the alert filter uses. Returns a dict with
    open + close ISO timestamps (with timezone), or None on failure
    (the planner can degrade gracefully if hours aren't available).
    """
    park_ids = {
        "magic_kingdom":     "75ea578a-adc8-4116-a54d-dccb60765ef9",
        "epcot":             "47f90d2c-e191-4239-a466-5892ef59a88b",
        "hollywood_studios": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
        "animal_kingdom":    "1c84a229-8862-4648-9c71-378ddd2c7693",
    }
    park_id = park_ids.get(park_key)
    if not park_id:
        return None

    import requests
    today_local = datetime.now(_EASTERN).date().isoformat()
    url = f"https://api.themeparks.wiki/v1/entity/{park_id}/schedule"
    try:
        r = requests.get(url, timeout=10)
        r.raise_for_status()
        data = r.json()
    except Exception:
        return None

    open_dt: datetime | None = None
    close_dt: datetime | None = None
    for entry in data.get("schedule", []):
        if entry.get("date") != today_local:
            continue
        if entry.get("type") not in ("OPERATING", "EXTRA_HOURS"):
            continue
        try:
            o = datetime.fromisoformat(entry["openingTime"])
            c = datetime.fromisoformat(entry["closingTime"])
        except (KeyError, ValueError):
            continue
        if open_dt is None or o < open_dt:
            open_dt = o
        if close_dt is None or c > close_dt:
            close_dt = c

    if open_dt is None or close_dt is None:
        return None
    now_et = datetime.now(_EASTERN)
    minutes_to_close = round((close_dt - now_et).total_seconds() / 60)
    return {
        "open": open_dt.isoformat(),
        "close": close_dt.isoformat(),
        "minutes_until_close": minutes_to_close,
    }


def _fetch_weather_forecast() -> dict[str, Any] | None:
    """Fetch current conditions + 6-hour forecast from Open-Meteo.

    No API key, no signup, no rate-limit headaches. Single request
    returns current state + hourly forecast for our fixed lat/lon.
    Returns None on failure — the planner falls back to "weather
    unknown, plan accordingly" rather than blocking the whole tool.

    Schema returned to the planner: a flat dict with the few fields
    Claude actually uses for ride selection (precipitation chance,
    weather code, temperature). The full Open-Meteo response is
    much richer; we trim it here so the model doesn't waste tokens
    parsing fields it won't use.
    """
    import requests
    url = (
        "https://api.open-meteo.com/v1/forecast"
        f"?latitude={_WDW_LAT}&longitude={_WDW_LON}"
        "&current=temperature_2m,precipitation,weather_code"
        "&hourly=temperature_2m,precipitation_probability,weather_code"
        "&temperature_unit=fahrenheit&precipitation_unit=inch"
        "&forecast_hours=6&timezone=America/New_York"
    )
    try:
        r = requests.get(url, timeout=10)
        r.raise_for_status()
        data = r.json()
    except Exception:
        return None

    current = data.get("current") or {}
    hourly = data.get("hourly") or {}
    times = hourly.get("time", [])
    temps = hourly.get("temperature_2m", [])
    precip = hourly.get("precipitation_probability", [])
    codes = hourly.get("weather_code", [])
    next_hours = [
        {
            "time": t,
            "temp_f": temps[i] if i < len(temps) else None,
            "precipitation_chance_pct": precip[i] if i < len(precip) else None,
            "weather_code": codes[i] if i < len(codes) else None,
        }
        for i, t in enumerate(times)
    ]
    return {
        "current": {
            "temp_f": current.get("temperature_2m"),
            "precipitation_inches": current.get("precipitation"),
            "weather_code": current.get("weather_code"),
        },
        "next_6h": next_hours,
        "weather_code_legend": (
            "Open-Meteo WMO codes: 0=clear, 1-3=mainly clear/partly cloudy/"
            "overcast, 45/48=fog, 51-67=drizzle/rain (light to heavy), "
            "71-77=snow, 80-82=rain showers, 95=thunderstorm, "
            "96/99=thunderstorm with hail. >=80 means rides may close "
            "(Disney pauses outdoor rides for lightning); 51-67 means "
            "ride continues but the queue/seats get wet."
        ),
    }


def _compute_load_vs_forecast(
    rides_out: list[dict],
) -> dict[str, Any] | None:
    """Compare each operating ride's current wait to today's forecast
    for the current ET hour. Aggregate into a park-level "today is
    running X% above/below forecast" signal.

    This is the always-on, point-in-time version of Phase C. Full
    forecast accuracy analytics (per-ride bias, time-of-day error,
    statistical confidence intervals) needs the per-poll wait history
    the C → B upgrade introduces. What we can do TODAY from existing
    data: snapshot ratio at the current moment.

    Aggregation is `sum(actual) / sum(predicted)` across sampled rides,
    which is equivalent to a wait-weighted mean of per-ride ratios.
    That weighting matters — a ride with predicted_wait=5 reporting
    actual_wait=20 is a 4x ratio but on tiny numbers (noise). A ride
    with predicted=60 reporting actual=75 is a 1.25x ratio on real
    minutes. Weighting by predicted wait pulls the signal toward the
    high-traffic rides that actually drive the user's experience.

    Excludes:
    - DOWN rides (no comparable forecast)
    - Rides with predicted wait <10 min (noise floor — small
      denominators produce flap in the ratio)
    - Rides missing either current STATE wait or a forecast entry
      for the current hour

    Returns None if no rides survive the exclusions (planner falls
    back to the raw forecast).
    """
    now_et = datetime.now(_EASTERN)
    current_hour = now_et.hour
    today_iso = now_et.date().isoformat()

    per_ride: list[dict[str, Any]] = []
    total_actual = 0
    total_predicted = 0

    for r in rides_out:
        if r.get("status") != "OPERATING":
            continue
        actual = r.get("wait_mins")
        forecast = r.get("forecast")
        if not actual or not forecast:
            continue
        # Find the forecast entry for the current ET hour today.
        # Upstream times are like "2026-05-10T17:00:00-04:00" — match
        # by date AND hour so we don't accidentally pick a previous
        # day's same-hour entry on overnight queries.
        predicted: int | None = None
        for entry in forecast:
            try:
                t = datetime.fromisoformat(entry["time"])
            except (KeyError, ValueError):
                continue
            t_et = t.astimezone(_EASTERN)
            if (
                t_et.date().isoformat() == today_iso
                and t_et.hour == current_hour
            ):
                predicted = entry.get("wait_mins")
                break
        if predicted is None or predicted < 10:
            continue
        ratio = round(actual / predicted, 2)
        per_ride.append({
            "ride_name": r["ride_name"],
            "actual_wait_mins": actual,
            "predicted_wait_this_hour": predicted,
            "ratio": ratio,
        })
        total_actual += actual
        total_predicted += predicted

    if not per_ride or total_predicted == 0:
        return None

    park_ratio = round(total_actual / total_predicted, 2)
    n = len(per_ride)

    # Confidence + interpretation. We don't have enough data to
    # compute formal confidence intervals (one snapshot per ride),
    # so this is sample-size + magnitude based.
    if n < 3:
        confidence = "low"
        interp = (
            f"Only {n} ride(s) sampled — treat the ratio as "
            f"directional only, don't lean on it heavily."
        )
    elif abs(park_ratio - 1.0) < 0.10:
        confidence = "high"
        interp = (
            f"Today running close to forecast ({int(park_ratio * 100)}% "
            f"of predicted, {n} rides sampled). Use forecast values as-is."
        )
    elif park_ratio > 1.0:
        pct = int((park_ratio - 1.0) * 100)
        confidence = "high" if n >= 5 else "medium"
        interp = (
            f"Today running ~{pct}% ABOVE forecast across {n} rides — "
            f"crowds heavier than predicted. Scale forecast peak values "
            f"by ~{park_ratio:.2f} when reasoning about cost-of-delay."
        )
    else:
        pct = int((1.0 - park_ratio) * 100)
        confidence = "high" if n >= 5 else "medium"
        interp = (
            f"Today running ~{pct}% BELOW forecast across {n} rides — "
            f"crowds lighter than predicted. Scale forecast peak values "
            f"by ~{park_ratio:.2f} when reasoning about cost-of-delay."
        )

    return {
        "park_load_ratio": park_ratio,
        "rides_sampled": n,
        "confidence": confidence,
        "interpretation": interp,
        "per_ride": per_ride,
    }


def _forecast_peak_in_window(
    forecast: list[dict], hours_ahead: int = 3
) -> dict[str, Any] | None:
    """Find the peak forecasted wait in the next N hours from now.

    Replaces the old full-horizon slope metric, which was misleading
    for non-monotonic forecasts: Pirates of the Caribbean humps
    10→40 (afternoon peak)→10 over the day, and a (last-first)/hours
    slope reports 0.0 — masking the real peak that an evening
    planner would walk into. Forward-looking peak captures the
    cost-of-delay signal that matters: "if you defer this ride,
    here's the worst wait you'd hit and how soon."

    Returns:
        Dict with peak_wait_mins, minutes_until_peak (from now), and
        peak_at (ISO timestamp). None if the forecast has no
        forward-looking entries with valid waits.
    """
    if not forecast:
        return None
    now_utc = datetime.now(timezone.utc)
    cutoff = now_utc + timedelta(hours=hours_ahead)

    peak_wait: int | None = None
    peak_time: datetime | None = None
    for entry in forecast:
        try:
            t = datetime.fromisoformat(entry["time"])
        except (KeyError, ValueError):
            continue
        # Compare in UTC so timezone-aware datetimes from upstream
        # (with `-04:00` offsets) compare cleanly.
        t_utc = t.astimezone(timezone.utc)
        if t_utc < now_utc or t_utc > cutoff:
            continue
        wait = entry.get("wait_mins")
        if not isinstance(wait, (int, float)):
            continue
        if peak_wait is None or wait > peak_wait:
            peak_wait = wait
            peak_time = t

    if peak_wait is None or peak_time is None:
        return None
    minutes_until = round(
        (peak_time.astimezone(timezone.utc) - now_utc).total_seconds() / 60, 1
    )
    return {
        "peak_wait_mins": peak_wait,
        "minutes_until_peak": minutes_until,
        "peak_at": peak_time.isoformat(),
    }


@mcp.tool()
def get_planning_context(
    park: str, ride_names: list[str]
) -> dict[str, Any]:
    """One-shot planner context: live status + forecast + DOWN history
    + location + park hours + weather, all for a list of rides.

    Use this when the user is planning what to ride next. Replaces
    5-10 separate calls to get_live_ride_status / get_ride_forecast /
    etc. Single round trip; consistent timestamp across all rides.

    HOW TO USE THE RESPONSE WHEN ORDERING RIDES:

    0. **Discover hard constraints first.** If the user gives you a
       multi-ride list without mentioning any of these, ASK ONCE
       before laying out the order — they materially change the plan
       and users often forget to volunteer them:
       - Table-service dining reservations (fixed start time, ~60-90
         min hold; missing the slot loses the reservation entirely)
       - Genie+ / Multi-Pass Lightning Lane reservations (1-hour
         return window per ride; standby wait effectively drops to
         ~10-15 min for that ride during its window)
       - Individual Lightning Lane / ILL (paid per-ride for top-tier
         attractions like TRON or Guardians; same 1-hour shape)
       - Virtual queue boarding groups (TRON, Tiana's, etc. — return
         window is set when the boarding group is called)
       Skip the question if the user already mentioned them. Treat
       each as a hard slot in the schedule and sequence other rides
       around it. When the user has an LL/ILL for a ride, note that
       you're skipping the standby line entirely for that ride.

       **Lightning Lane scheduling mechanics (practical detail
       Claude might not naturally know):**
       - The 1-hour window has informal buffers: Disney typically
         allows entry ~5 min before the window opens and ~15 min
         after it closes, though enforcement varies. **Default
         policy: use these buffers strategically when they
         materially improve the plan** (saves a cross-park walk,
         fits an extra ride, avoids skipping a marquee attraction).
         Most experienced guests routinely use the grace and it's
         reliable enough to plan against. NOTE the assumption ONCE
         per itinerary: "Plan assumes typical Disney grace on LL
         windows (~5 min early / ~15 min late). If grace tightens
         on a given day, fall back to the nominal windows."
         Don't re-flag for every individual ride — that's noise.
         Switch to conservative-only (nominal windows, no grace)
         only when the user explicitly asks, OR when the buffer
         use is unusually aggressive (more than 10 min outside the
         nominal window on either side).
       - The LL line itself is NOT zero-wait. Plan ~10-15 min for
         the LL queue (can hit 20-25 min during peak hours). Total
         time from "tap in" to "off the ride" is usually ~25-30 min.
       - Factor in walking time to reach the LL window. If the user
         is across the park (>500m by the lat/lon data) when the
         window opens, build in the walk — don't have them book-end
         the window with travel time on both sides.
       - If two LL windows overlap, the user has to pick one. Flag
         the conflict and ask which is the priority.

    1. **Cost-of-delay rule** (most important). The fields you want:
       `forecast_peak_next_3h_mins` (worst forecasted wait in the next
       3 hours) and `forecast_minutes_until_peak` (how soon that peak
       hits). For each ride, marginal cost of deferring it ≈
       max(0, forecast_at_deferred_time - current_wait_mins). Order
       by DESCENDING cost-of-delay, NOT by ascending current wait.
       Show your math: "If I do TRON first (~80 min round trip),
       Pirates' wait at +80 min would be ~40 (its peak hits in 60
       min and holds), so deferring Pirates costs +30 min. If I do
       Pirates first (~25 min), TRON's wait at +25 min is still ~85
       (flat over the next 3h), so deferring TRON costs ~0. Pirates
       first." The full `forecast` array is also returned so you can
       look up exact future-wait values at specific times when needed.

    1.5. **Today-vs-forecast correction.** The top-level
       `today_vs_forecast` field compares each operating ride's
       CURRENT wait to what today's forecast predicted for the
       current ET hour, aggregated park-wide. If `park_load_ratio`
       is materially different from 1.0 (>10% off), today's actual
       crowd is heavier or lighter than the forecast model expected.
       When reasoning about cost-of-delay, scale forecast peak
       values by this ratio. Example: ratio=1.23, forecast says
       Pirates peaks at 40 in 60 min → expected actual peak is
       ~49 min. Note the calibration ONCE in your response ("Today
       is running 23% above forecast — I've adjusted the peak
       estimates accordingly") rather than re-mentioning it per
       ride. Confidence levels: `low` (<3 rides sampled, treat as
       directional only); `medium`/`high` (5+ rides, reliable
       enough to scale by). If confidence is low or the field is
       absent, use forecast values as-is.

    2. **DOWN-state rides.** Use `down_duration_mins` and
       `typical_down_cluster_mins` to estimate when they'll come back.
       `cluster_progress_pct` near 0% = early, plan ~typical more min;
       near 100% = could come back any minute. Do NOT infer return
       time from `current_ll_offer.return_start` — Lightning Lane
       offers are unrelated to operational status.

    3. **Proximity grouping.** Each ride has `location.lat/lon`. Use
       haversine distance to identify clusters (rides within ~250m
       are in adjacent lands). Other things equal, prefer back-to-back
       rides in the same cluster to reduce walking.

    4. **Feasibility check — warn the user if the wishlist won't fit.**
       BEFORE presenting the order, sanity-check that the plan fits
       in the time available. Estimate per ride:
         time_per_ride ≈ current_wait_mins + 10 min ride duration
                         + walking time to next ride
       Walking: ~5 min for adjacent lands (<300m), ~10 min for cross-
       park hops (>500m, e.g. Adventureland to Tomorrowland). Use the
       lat/lon distances to be specific.
       Total budget = `park_hours.minutes_until_close` minus dining
       hold(s) minus reservation/LL window buffers minus a 30-min
       safety margin (bathroom, longer-than-forecast queues, etc.).
       If total_estimated > total_budget, **flag it explicitly and
       generate 2-3 alternate full plans** rather than asking the
       user "which to drop." Each alternate should be a complete
       ordered itinerary so the user can compare lived experiences,
       not just lists of dropped rides. Format each as a short
       labeled bundle:

         **Plan A — "Skip TRON, do everything else"**
         1. Pirates (10 min, 6:00 PM)
         2. Big Thunder (60 min, 6:30 PM)
         3. Haunted Mansion (recovers ~6:30, do at 7:00)
         4. Space Mountain (last, recovers ~8:30)
         Tradeoff: skips the marquee coaster but fits 4 rides
         comfortably.

         **Plan B — "TRON-focused: 3 rides including TRON"**
         1. TRON (65 min, NOW)
         2. Big Thunder (next door after TRON, 60 min ~7:30)
         3. Space Mountain (last, recovers ~8:30)
         Tradeoff: skips both Mansion and Pirates to lock in TRON
         + late-night Space Mountain.

         **Plan C — "Adventureland cluster: 3 quick rides nearby"**
         1. Pirates (10 min)
         2. Haunted Mansion (when it recovers ~6:30)
         3. Big Thunder (adjacent to Mansion)
         Tradeoff: tightest walking, drops the Tomorrowland rides
         but you finish with energy left for fireworks/dining.

       Pick alternatives that highlight DIFFERENT tradeoffs — drop
       one big ride vs drop several small ones; cluster by proximity
       vs spread across the park; drop based on uncertainty (DOWN
       rides) vs drop based on cost. 2-3 plans is the right number,
       not 5. Then ask "Which plan fits your priorities?" so the
       user picks intent rather than reverse-engineering a list of
       skipped rides.

    5. **Meal/break windows.** If the user mentions wanting to eat or
       take a break in a specific time window ("quick-service dinner
       between 5-7pm" / "let's stop for snacks around 3"), treat it
       as a fixed ~30-45 min hold in the schedule and sequence rides
       to put them in the right area when the window starts. Use your
       general knowledge of WDW dining locations (Pecos Bill's in
       Frontierland, Cosmic Ray's in Tomorrowland near Space Mountain,
       Pinocchio Village Haus in Fantasyland, Columbia Harbour House
       in Liberty Square near Haunted Mansion, etc.) to suggest a
       specific spot near whichever ride you'd be at when the window
       opens. Acknowledge this is a general-knowledge suggestion, not
       a live-data lookup — wait times and operating status of
       restaurants aren't currently in MM's data.

    6. **Weather + heat.** Outdoor rides (coasters like Big Thunder,
       TRON, Splash, Slinky Dog; water rides like Pirates, Splash,
       Kali) close for lightning (weather_code 95/96/99). Heavy rain
       (weather_code 80+ or precipitation_chance > 70%) means outdoor
       rides become miserable even when they stay open. Florida
       afternoon heat is its own factor — outdoor queues with no
       shade are uncomfortable above ~85°F and brutal above ~90°F.
       Use general Disney knowledge to classify each ride as
       indoor / outdoor / partially-covered. Then sequence:
       - Imminent thunderstorms in `weather.next_6h` → push outdoor
         rides to the clear hours, do indoor rides during the storm.
       - Hot now (>~88°F) but cooler later in the forecast → defer
         outdoor rides to the cooler window, do indoor rides now.
       - Currently cooler than later → do outdoor rides now while
         comfortable, save indoor for when heat peaks.
       - Always-comfortable day → ignore temperature, decide on
         cost-of-delay + proximity alone.

    Args:
        park: Park key or human name. Accepts 'magic_kingdom',
            'Magic Kingdom', 'MK', etc.
        ride_names: List of ride names (substring match, case
            insensitive). Each name resolved against the historical
            snapshot. Unresolved names appear in `unresolved` instead
            of being silently dropped.

    Returns:
        Dict with park, current_time_et, park_hours (open/close/
        minutes_until_close), weather (current + 6h forecast), rides
        (list with full per-ride context), and unresolved (list of
        ride_names that couldn't be matched). On AWS auth failure for
        the live-data portion, falls back to per-ride error blocks
        rather than dropping the whole call.
    """
    park_key = _normalize_park(park)
    now_et = datetime.now(_EASTERN)

    # Resolve every ride name first (offline lookup against the
    # snapshot). Unmatched names go into `unresolved` so the model
    # can flag them to the user instead of silently planning around
    # the rides it could resolve.
    resolved: list[dict[str, Any]] = []
    unresolved: list[str] = []
    for name in ride_names:
        try:
            r = _find_ride(name)
        except ValueError:
            unresolved.append(name)
            continue
        resolved.append(r)

    table = None
    table_error: dict[str, Any] | None = None
    try:
        table = _ddb_table()
    except Exception as e:
        err = _aws_error_payload(e)
        table_error = err if err is not None else {
            "error": "DDB connection failed",
            "error_message": str(e),
        }

    locations = _locations()
    rides_out: list[dict[str, Any]] = []

    for ride in resolved:
        rid = ride["ride_id"]
        out: dict[str, Any] = {
            "ride_name": ride["ride_name"],
            "ride_id": rid,
            "park_key": ride.get("park_key"),
        }
        # Static location lookup — cheap, always fill it in if we have it
        loc = locations.get(rid)
        if loc:
            out["location"] = {"lat": loc["lat"], "lon": loc["lon"]}

        if table_error is not None or table is None:
            out.update(table_error or {"error": "DDB unavailable"})
            rides_out.append(out)
            continue

        # 1. STATE row (current status, wait, LL, last_seen, last_forecast_at)
        try:
            state_resp = table.get_item(
                Key={"PK": f"RIDE#{rid}", "SK": "STATE"}
            )
            state = _convert_decimals(state_resp.get("Item")) if state_resp.get("Item") else None
        except Exception as e:
            err = _aws_error_payload(e)
            out.update(err or {"error": "STATE read failed", "error_message": str(e)})
            rides_out.append(out)
            continue

        if not state:
            out["live_state_available"] = False
            rides_out.append(out)
            continue

        out["status"] = state.get("status")
        out["wait_mins"] = state.get("wait_mins")
        out["current_ll_offer"] = state.get("ll")
        out["last_seen"] = state.get("last_seen")
        out["last_forecast_at"] = state.get("last_forecast_at")

        # 2. DOWN enrichment (only when status=DOWN)
        if state.get("status") == "DOWN":
            try:
                ds_resp = table.get_item(
                    Key={"PK": f"RIDE#{rid}", "SK": "DOWN_SINCE"}
                )
                ds_item = ds_resp.get("Item")
                if ds_item and ds_item.get("down_since"):
                    out["down_since"] = ds_item["down_since"]
                    try:
                        down_dt = datetime.fromisoformat(ds_item["down_since"])
                        elapsed = datetime.now(timezone.utc) - down_dt
                        out["down_duration_mins"] = round(
                            elapsed.total_seconds() / 60, 1
                        )
                    except ValueError:
                        pass
            except Exception:
                pass

            clusters = ride.get("down_clusters", [])
            durations = sorted(
                c["duration_minutes"] for c in clusters
                if isinstance(c.get("duration_minutes"), (int, float))
            )
            if durations:
                mid = len(durations) // 2
                if len(durations) % 2 == 1:
                    median = durations[mid]
                else:
                    median = (durations[mid - 1] + durations[mid]) / 2
                out["typical_down_cluster_mins"] = round(median, 1)
                out["historical_cluster_count"] = len(durations)
                cur = out.get("down_duration_mins")
                if cur is not None and median > 0:
                    out["cluster_progress_pct"] = round(100.0 * cur / median, 1)

        # 3. Latest forecast snapshot
        try:
            f_resp = table.query(
                KeyConditionExpression="PK = :pk AND begins_with(SK, :sk)",
                ExpressionAttributeValues={
                    ":pk": f"RIDE#{rid}",
                    ":sk": "FORECAST#",
                },
                ScanIndexForward=False,
                Limit=1,
            )
            f_items = f_resp.get("Items", [])
            if f_items:
                f_item = _convert_decimals(f_items[0])
                forecast = f_item.get("forecast", []) or []
                out["forecast_polled_at"] = f_item.get("polled_at")
                out["forecast"] = forecast
                # Peak-in-next-3h is the cost-of-delay signal that
                # matters for planning. The old full-horizon slope
                # was misleading for hump-shaped curves like Pirates
                # of the Caribbean (afternoon peak → drops by close).
                peak = _forecast_peak_in_window(forecast, hours_ahead=3)
                if peak is not None:
                    out["forecast_peak_next_3h_mins"] = peak["peak_wait_mins"]
                    out["forecast_minutes_until_peak"] = peak["minutes_until_peak"]
                    out["forecast_peak_at"] = peak["peak_at"]
            else:
                # Common when ride is currently DOWN — themeparks.wiki
                # stops forecasting DOWN rides. Note that explicitly
                # rather than leaving the field absent ambiguously.
                out["forecast"] = None
                out["forecast_unavailable_reason"] = (
                    "No forecast row in DDB. Usually means the upstream "
                    "API isn't predicting this ride right now (most often "
                    "because it's DOWN, walk-up, or no-queue)."
                )
        except Exception:
            out["forecast"] = None

        rides_out.append(out)

    return {
        "park": park_key,
        "current_time_et": now_et.isoformat(),
        "park_hours": _fetch_park_hours_today(park_key),
        "weather": _fetch_weather_forecast(),
        "today_vs_forecast": _compute_load_vs_forecast(rides_out),
        "rides": rides_out,
        "unresolved": unresolved,
    }


@mcp.tool()
def find_rides_matching(
    park: str | None = None,
    max_downtime_pct: float | None = None,
    min_downtime_pct: float | None = None,
    min_avg_wait: int | None = None,
    max_avg_wait: int | None = None,
    sort_by: str = "downtime_pct",
    sort_desc: bool = True,
    limit: int = 20,
) -> dict[str, Any]:
    """Filter and sort rides across the analytics snapshot.

    Use this to answer questions like 'which rides have low downtime
    but high waits?' or 'what's the most reliable ride at Magic
    Kingdom?'

    Args:
        park: Optional. Restrict to one park (key or human name).
        max_downtime_pct: Optional. Only rides at or below this %.
        min_downtime_pct: Optional. Only rides at or above this %.
        min_avg_wait: Optional. Only rides with avg wait >= this (min).
        max_avg_wait: Optional. Only rides with avg wait <= this (min).
        sort_by: One of 'downtime_pct', 'avg_wait', 'max_wait',
            'total_polls', 'ride_name'. Default 'downtime_pct'.
        sort_desc: Whether to sort descending (default True).
        limit: Max rows to return. Default 20, max 100.

    Returns:
        Dict with the resolved filter, the sort, the matched count,
        and a list of ride summaries (ride_name, park_key,
        downtime_pct, avg_wait, max_wait, total_polls).
    """
    rides = list(_snapshot()["rides"])
    park_key: str | None = None
    if park is not None:
        park_key = _normalize_park(park)
        rides = [r for r in rides if r["park_key"] == park_key]

    if max_downtime_pct is not None:
        rides = [r for r in rides if r["downtime_pct"] <= max_downtime_pct]
    if min_downtime_pct is not None:
        rides = [r for r in rides if r["downtime_pct"] >= min_downtime_pct]
    if min_avg_wait is not None:
        rides = [r for r in rides if (r.get("avg_wait") or 0) >= min_avg_wait]
    if max_avg_wait is not None:
        rides = [r for r in rides if (r.get("avg_wait") or 0) <= max_avg_wait]

    valid_sorts = {"downtime_pct", "avg_wait", "max_wait", "total_polls", "ride_name"}
    if sort_by not in valid_sorts:
        raise ValueError(
            f"sort_by must be one of {sorted(valid_sorts)}, got '{sort_by}'"
        )

    def _key(r: dict[str, Any]) -> Any:
        v = r.get(sort_by)
        if sort_by == "ride_name":
            return (v or "").lower()
        # Treat None as -inf when sorting so it lands at the bottom of
        # a descending sort (and the top of an ascending one — which
        # matches the "show me the worst data first" intent).
        return v if v is not None else float("-inf")

    rides.sort(key=_key, reverse=sort_desc)
    limit = max(1, min(limit, 100))
    return {
        "filter": {
            "park": park_key,
            "max_downtime_pct": max_downtime_pct,
            "min_downtime_pct": min_downtime_pct,
            "min_avg_wait": min_avg_wait,
            "max_avg_wait": max_avg_wait,
        },
        "sort_by": sort_by,
        "sort_desc": sort_desc,
        "match_count": len(rides),
        "rides": [
            {
                "ride_name": r["ride_name"],
                "park_key": r["park_key"],
                "downtime_pct": r["downtime_pct"],
                "avg_wait": r.get("avg_wait"),
                "max_wait": r.get("max_wait"),
                "total_polls": r["total_polls"],
            }
            for r in rides[:limit]
        ],
    }


if __name__ == "__main__":
    mcp.run()
